"""
backend/app/models/skill.py
----------------------------
ORM model for the ``skills`` table.

Table overview
--------------
``skills`` stores individual competencies tied to a specific career profession.
Each skill belongs to exactly one ``Profession`` (one-to-many relationship).
Skills power the platform's skill-gap analysis, learning roadmaps, and AI
interview preparation features.

Columns
-------
id              UUID PK — Python-generated (uuid4).
name            VARCHAR(255) NOT NULL — human display name of the skill.
description     TEXT NULLABLE — rich Markdown description of the skill.
difficulty      VARCHAR(20) NOT NULL — Enum: 'Beginner', 'Intermediate', 'Advanced'.
category        VARCHAR(100) NULLABLE — e.g. "Programming", "Soft Skills".
profession_id   UUID FK → professions.id NOT NULL — owning profession.
created_at      TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at      TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Relationships
-------------
skill.profession → Profession  (many-to-one, ``back_populates="skills"``)

Registration
------------
Add the following line in ``app/db/base.py`` after creating this file::

    from app.models.skill import Skill  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Skill(Base):
    """SQLAlchemy 2.x ORM model for the ``skills`` table.

    Represents an individual competency or technology associated with a
    career profession.  One ``Profession`` can have many ``Skill`` records
    (one-to-many).

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        name: Human-readable skill name (e.g. "Python", "Data Structures").
        description: Optional long-form Markdown description of the skill.
        difficulty: Categorical difficulty level — one of
            ``'Beginner'``, ``'Intermediate'``, or ``'Advanced'``.
        category: Optional grouping category (e.g. "Programming", "Soft Skills").
        profession_id: Foreign key to the owning ``Profession`` row.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        profession: ORM relationship back to the owning ``Profession`` instance.
    """

    __tablename__ = "skills"

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Name ─────────────────────────────────────────────────────────────── #
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True,
        comment="Human-readable skill name (e.g. 'Python', 'Data Structures').",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional Markdown description of the skill.",
    )

    # ── Difficulty ───────────────────────────────────────────────────────── #
    difficulty: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'.",
    )

    # ── Category ─────────────────────────────────────────────────────────── #
    category: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
        comment="Grouping category e.g. 'Programming', 'Soft Skills', 'DevOps'.",
    )

    # ── Foreign key — owning Profession ──────────────────────────────────── #
    profession_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("professions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → professions.id.  Skill is deleted when Profession is hard-deleted.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    profession: Mapped["Profession"] = relationship(  # type: ignore[name-defined]
        "Profession",
        back_populates="skills",
        lazy="select",
    )



    roadmap_steps: Mapped[list["RoadmapStep"]] = relationship(  # type: ignore[name-defined]
        "RoadmapStep",
        back_populates="skill",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log (no secrets)."""
        return (
            f"Skill("
            f"id={self.id!r}, "
            f"name={self.name!r}, "
            f"difficulty={self.difficulty!r}, "
            f"profession_id={self.profession_id!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable name — used in template rendering and f-string logs."""
        return self.name
