"""
services/agent-service/app/api/v1/agent4/router.py
----------------------------------------------------
Agent 4 API — AI mock interview conductor.
"""
from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.agents.agent4_interview import interview_agent
from app.db.session import get_db
from app.schemas.interview import (
    AnswerFeedbackOut,
    AnswerRequest,
    InterviewOut,
    InterviewStartRequest,
    NextQuestionOut,
)

router = APIRouter()


@router.post(
    "/interviews/start",
    response_model=InterviewOut,
    status_code=status.HTTP_201_CREATED,
    summary="Agent 4 — Start AI mock interview",
)
def start_interview(
    payload: InterviewStartRequest, db: Session = Depends(get_db)
) -> InterviewOut:
    """
    **Agent 4**: Starts a professional AI mock interview using questions generated by Agent 3.
    """
    try:
        interview = interview_agent.start_interview(db, payload)
        return InterviewOut.model_validate(interview)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))


@router.get(
    "/interviews/{interview_id}/question",
    response_model=NextQuestionOut,
    summary="Get current interview question",
)
def get_current_question(
    interview_id: uuid.UUID, db: Session = Depends(get_db)
) -> NextQuestionOut:
    """Returns the current (unanswered) interview question."""
    question = interview_agent.get_next_question(db, interview_id)
    if not question:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No question found. Interview may be complete.",
        )
    return question


@router.post(
    "/interviews/answer",
    response_model=AnswerFeedbackOut,
    summary="Agent 4 — Submit answer and get AI feedback",
)
def submit_answer(
    payload: AnswerRequest, db: Session = Depends(get_db)
) -> AnswerFeedbackOut:
    """
    **Agent 4**: Evaluates the student's answer and returns feedback.
    Also returns the next question or marks interview as complete.
    """
    try:
        feedback = interview_agent.submit_answer(db, payload)
        return feedback
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))


@router.get(
    "/interviews/{interview_id}",
    response_model=InterviewOut,
    summary="Get interview session",
)
def get_interview(interview_id: uuid.UUID, db: Session = Depends(get_db)) -> InterviewOut:
    interview = interview_agent.get_interview(db, interview_id)
    if not interview:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Interview not found.")
    return InterviewOut.model_validate(interview)


@router.get(
    "/interviews/student/{student_id}",
    response_model=list[InterviewOut],
    summary="Get all interviews for a student",
)
def get_student_interviews(
    student_id: uuid.UUID, db: Session = Depends(get_db)
) -> list[InterviewOut]:
    interviews = interview_agent.get_student_interviews(db, student_id)
    return [InterviewOut.model_validate(i) for i in interviews]
