"""
backend/app/models/career_roadmap.py
--------------------------------------
ORM models for the ``career_roadmaps`` and ``roadmap_steps`` tables.

Table overview
--------------
``career_roadmaps``
    A structured, ordered learning plan that guides a learner through a
    complete career progression for a given Profession.  One Profession may
    have multiple Roadmaps (e.g. "Fast Track", "Comprehensive", "Part-Time").
    Each Roadmap is composed of an ordered list of RoadmapSteps.

``roadmap_steps``
    An individual step within a CareerRoadmap.  Each step references exactly
    one Skill and carries sequencing, required/optional flag, and an estimated
    hour commitment.  Steps are uniquely ordered within their parent Roadmap
    via a UNIQUE constraint on (roadmap_id, step_order).

CareerRoadmap Columns
---------------------
id               UUID PK — Python-generated (uuid4).
profession_id    UUID FK → professions.id NOT NULL — owning career profession.
title            VARCHAR(500) NOT NULL — human display title of the roadmap.
description      TEXT NULLABLE — rich Markdown description of the roadmap.
estimated_months INTEGER NOT NULL DEFAULT 1 — estimated months to completion.
difficulty       VARCHAR(20) NOT NULL — Enum: 'Beginner', 'Intermediate', 'Advanced'.
is_active        BOOLEAN NOT NULL DEFAULT true — soft-delete / visibility flag.
created_at       TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at       TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

RoadmapStep Columns
-------------------
id               UUID PK — Python-generated (uuid4).
roadmap_id       UUID FK → career_roadmaps.id NOT NULL — parent roadmap.
skill_id         UUID FK → skills.id NOT NULL — skill covered at this step.
step_order       INTEGER NOT NULL — 1-based position within the roadmap.
required         BOOLEAN NOT NULL DEFAULT true — required vs. optional step.
estimated_hours  NUMERIC(7,2) NOT NULL DEFAULT 0 — expected hours for step.
created_at       TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at       TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Constraints
-----------
career_roadmaps: No composite uniqueness — multiple roadmaps per profession
    with different titles are allowed.
roadmap_steps:   UNIQUE (roadmap_id, step_order) — no two steps share the
                 same position within a roadmap.
                 UNIQUE (roadmap_id, skill_id) — a skill appears at most
                 once per roadmap.
                 CHECK  (step_order >= 1) — ordering starts at 1.
                 CHECK  (estimated_hours >= 0) — time cannot be negative.

Relationships
-------------
career_roadmap.profession → Profession  (many-to-one)
career_roadmap.steps      → [RoadmapStep]  (one-to-many, ordered)
roadmap_step.roadmap      → CareerRoadmap  (many-to-one)
roadmap_step.skill        → Skill          (many-to-one)

Registration
------------
Add the following lines in ``app/db/base.py``::

    from app.models.career_roadmap import CareerRoadmap, RoadmapStep
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


# =========================================================================== #
#  CareerRoadmap model                                                          #
# =========================================================================== #


class CareerRoadmap(Base):
    """SQLAlchemy 2.x ORM model for the ``career_roadmaps`` table.

    Represents a structured, titled learning plan for a specific career
    profession.  One ``Profession`` can have many ``CareerRoadmap`` records
    (e.g. beginner track vs. advanced accelerated track).

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        profession_id: FK to the ``Profession`` this roadmap belongs to.
        title: Human-readable roadmap title.
        description: Optional long-form Markdown description.
        estimated_months: Estimated months needed to complete the roadmap.
        difficulty: Categorical difficulty — one of ``'Beginner'``,
            ``'Intermediate'``, or ``'Advanced'``.
        is_active: ``True`` = roadmap is visible to learners.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        profession: ORM relationship to the owning ``Profession``.
        steps: Ordered list of ``RoadmapStep`` records for this roadmap.
    """

    __tablename__ = "career_roadmaps"

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — Profession ─────────────────────────────────────────── #
    profession_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("professions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → professions.id. Roadmap is deleted when Profession is deleted.",
    )

    # ── Title ────────────────────────────────────────────────────────────── #
    title: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        index=True,
        comment="Human-readable roadmap title (e.g. 'Full-Stack Developer Path').",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional Markdown description of the roadmap.",
    )

    # ── Estimated months ─────────────────────────────────────────────────── #
    estimated_months: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default="1",
        comment="Estimated calendar months to complete the full roadmap. Must be >= 1.",
    )

    # ── Difficulty ───────────────────────────────────────────────────────── #
    difficulty: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'.",
    )

    # ── Soft-delete flag ──────────────────────────────────────────────────── #
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        index=True,
        comment="False = hidden from learners. Prefer over hard DELETE.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    profession: Mapped["Profession"] = relationship(  # type: ignore[name-defined]
        "Profession",
        back_populates="career_roadmaps",
        lazy="select",
    )

    steps: Mapped[list["RoadmapStep"]] = relationship(
        "RoadmapStep",
        back_populates="roadmap",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="RoadmapStep.step_order",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"CareerRoadmap("
            f"id={self.id!r}, "
            f"title={self.title!r}, "
            f"profession_id={self.profession_id!r}, "
            f"difficulty={self.difficulty!r}, "
            f"is_active={self.is_active!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable title — used in f-string logs."""
        return self.title


# =========================================================================== #
#  RoadmapStep model                                                            #
# =========================================================================== #


class RoadmapStep(Base):
    """SQLAlchemy 2.x ORM model for the ``roadmap_steps`` table.

    Represents a single ordered step inside a ``CareerRoadmap``.  Each step
    links the roadmap to one ``Skill`` and annotates it with ordering,
    required/optional flag, and expected time commitment.

    A UNIQUE constraint on ``(roadmap_id, step_order)`` ensures no two steps
    share the same position within a roadmap.
    A UNIQUE constraint on ``(roadmap_id, skill_id)`` ensures each skill
    appears at most once per roadmap.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        roadmap_id: FK to the parent ``CareerRoadmap``.
        skill_id: FK to the ``Skill`` covered at this step.
        step_order: 1-based integer ordering this step within the roadmap.
        required: ``True`` = learners must complete this step.
        estimated_hours: Expected hours to complete this step (>= 0).
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        roadmap: ORM relationship to the parent ``CareerRoadmap``.
        skill: ORM relationship to the referenced ``Skill``.
    """

    __tablename__ = "roadmap_steps"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        UniqueConstraint(
            "roadmap_id",
            "step_order",
            name="uq_roadmap_steps_roadmap_order",
        ),
        UniqueConstraint(
            "roadmap_id",
            "skill_id",
            name="uq_roadmap_steps_roadmap_skill",
        ),
        CheckConstraint(
            "step_order >= 1",
            name="ck_roadmap_steps_order_positive",
        ),
        CheckConstraint(
            "estimated_hours >= 0",
            name="ck_roadmap_steps_hours_non_negative",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — CareerRoadmap ──────────────────────────────────────── #
    roadmap_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("career_roadmaps.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → career_roadmaps.id. Step is deleted with its roadmap.",
    )

    # ── Foreign key — Skill ──────────────────────────────────────────────── #
    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("skills.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="FK → skills.id. RESTRICT prevents deleting a skill in-use.",
    )

    # ── Step order ───────────────────────────────────────────────────────── #
    step_order: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="1-based position of this step within the roadmap. Unique per roadmap.",
    )

    # ── Required flag ────────────────────────────────────────────────────── #
    required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        index=True,
        comment="True = mandatory step. False = optional / enrichment material.",
    )

    # ── Estimated hours ──────────────────────────────────────────────────── #
    estimated_hours: Mapped[float] = mapped_column(
        Numeric(precision=7, scale=2),
        nullable=False,
        default=0,
        server_default="0",
        comment="Estimated hours to complete this step. Must be >= 0.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    roadmap: Mapped["CareerRoadmap"] = relationship(
        "CareerRoadmap",
        back_populates="steps",
        lazy="select",
    )

    skill: Mapped["Skill"] = relationship(  # type: ignore[name-defined]
        "Skill",
        back_populates="roadmap_steps",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"RoadmapStep("
            f"id={self.id!r}, "
            f"roadmap_id={self.roadmap_id!r}, "
            f"skill_id={self.skill_id!r}, "
            f"step_order={self.step_order!r}, "
            f"required={self.required!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary — used in f-string logs."""
        return f"Step {self.step_order} (roadmap={self.roadmap_id}, skill={self.skill_id})"
