"""
backend/app/models/interview_question.py
-----------------------------------------
ORM models for ``interview_questions`` and ``interview_answers`` tables.

Table overview
--------------
``interview_questions``
    Stores individual interview questions generated for a specific ``Interview``.
    Questions are ordered sequentially via ``order_no``.

``interview_answers``
    Stores a learner's response to an ``InterviewQuestion``, including the
    free-text answer and the time taken in seconds.

InterviewQuestion Columns
-------------------------
id             UUID PK — Python-generated (uuid4).
interview_id   UUID FK → interviews.id NOT NULL — parent interview session.
question       TEXT NOT NULL — interview question prompt text.
question_type  VARCHAR(20) NOT NULL DEFAULT 'Technical' — Enum: 'Technical', 'Behavioral'.
difficulty     VARCHAR(20) NOT NULL DEFAULT 'Medium' — Enum: 'Easy', 'Medium', 'Hard'.
order_no       INTEGER NOT NULL DEFAULT 1 — 1-based sequence order.
created_at     TIMESTAMPTZ NOT NULL — creation timestamp.

InterviewAnswer Columns
-----------------------
id                 UUID PK — Python-generated (uuid4).
question_id        UUID FK → interview_questions.id NOT NULL — answered question.
user_id            UUID FK → users.id NOT NULL — learner answering the question.
answer_text        TEXT NULLABLE — student's free-text response.
time_taken_seconds INTEGER NOT NULL DEFAULT 0 — time spent answering in seconds.
created_at         TIMESTAMPTZ NOT NULL — creation timestamp.

Constraints
-----------
interview_questions:
    CHECK (order_no >= 1)
interview_answers:
    CHECK (time_taken_seconds >= 0)
    UNIQUE (question_id, user_id) — one answer per user per question.

Relationships
-------------
question.interview → Interview           (many-to-one, bidirectional)
question.answers   → [InterviewAnswer]   (one-to-many, bidirectional)
answer.question    → InterviewQuestion   (many-to-one, bidirectional)
answer.user        → User                (many-to-one, unidirectional)

Registration
------------
Add the following lines in ``app/db/base.py``::

    from app.models.interview_question import InterviewQuestion, InterviewAnswer  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.interview import Interview  # noqa: F401
    from app.models.user import User  # noqa: F401


# =========================================================================== #
#  InterviewQuestion model                                                    #
# =========================================================================== #


class InterviewQuestion(Base):
    """SQLAlchemy 2.x ORM model for the ``interview_questions`` table.

    Represents a single question within an interview session.

    Attributes:
        id: UUID primary key.
        interview_id: FK to parent ``Interview``.
        question: Question prompt text.
        question_type: 'Technical' or 'Behavioral'.
        difficulty: 'Easy', 'Medium', or 'Hard'.
        order_no: 1-based order index.
        created_at: Creation timestamp.
        interview: Parent ``Interview`` ORM instance.
        answers: List of ``InterviewAnswer`` instances.
    """

    __tablename__ = "interview_questions"

    __table_args__ = (
        CheckConstraint(
            "order_no >= 1",
            name="ck_interview_questions_order_positive",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key ──────────────────────────────────────────────────────── #
    interview_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interviews.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → interviews.id. Question deleted when interview is deleted.",
    )

    # ── Question details ─────────────────────────────────────────────────── #
    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The text prompt of the interview question.",
    )

    question_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Technical",
        server_default="Technical",
        comment="Question type: 'Technical' or 'Behavioral'.",
    )

    difficulty: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Medium",
        server_default="Medium",
        comment="Difficulty: 'Easy', 'Medium', or 'Hard'.",
    )

    order_no: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default="1",
        comment="1-based sequence order of the question in the interview.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of creation.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    interview: Mapped["Interview"] = relationship(
        "Interview",
        back_populates="questions",
        lazy="select",
    )

    answers: Mapped[list["InterviewAnswer"]] = relationship(
        "InterviewAnswer",
        back_populates="question",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"InterviewQuestion("
            f"id={self.id!r}, "
            f"interview_id={self.interview_id!r}, "
            f"order_no={self.order_no!r}, "
            f"type={self.question_type!r}"
            f")"
        )


# =========================================================================== #
#  InterviewAnswer model                                                       #
# =========================================================================== #


class InterviewAnswer(Base):
    """SQLAlchemy 2.x ORM model for the ``interview_answers`` table.

    Represents a student's answer to a specific ``InterviewQuestion``.

    Attributes:
        id: UUID primary key.
        question_id: FK to ``InterviewQuestion``.
        user_id: FK to ``User``.
        answer_text: Free-text answer provided by the learner.
        time_taken_seconds: Time spent answering in seconds.
        created_at: Timestamp when answer was submitted.
        question: ``InterviewQuestion`` ORM instance.
        user: ``User`` ORM instance.
    """

    __tablename__ = "interview_answers"

    __table_args__ = (
        CheckConstraint(
            "time_taken_seconds >= 0",
            name="ck_interview_answers_time_non_negative",
        ),
        UniqueConstraint(
            "question_id",
            "user_id",
            name="uq_interview_answers_question_user",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4.",
    )

    # ── Foreign keys ─────────────────────────────────────────────────────── #
    question_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_questions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → interview_questions.id.",
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → users.id.",
    )

    # ── Answer details ───────────────────────────────────────────────────── #
    answer_text: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Student's free-text response.",
    )

    time_taken_seconds: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Time spent answering in seconds.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of creation.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    question: Mapped["InterviewQuestion"] = relationship(
        "InterviewQuestion",
        back_populates="answers",
        lazy="select",
    )

    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"InterviewAnswer("
            f"id={self.id!r}, "
            f"question_id={self.question_id!r}, "
            f"user_id={self.user_id!r}"
            f")"
        )
