"""
backend/app/models/interview.py
---------------------------------
ORM model for the ``interviews`` table.

Table overview
--------------
``interviews``
    Stores scheduled mock interviews for learners based on task performance.
    Each interview links one ``User`` to one ``Task`` and records the schedule,
    duration, status, and optional meeting link.

Columns
-------
id                UUID PK — Python-generated (uuid4).
user_id           UUID FK → users.id NOT NULL — learner scheduled for interview.
task_id           UUID FK → tasks.id NOT NULL — task associated with the interview.
scheduled_at      TIMESTAMPTZ NOT NULL — scheduled start time (UTC).
duration_minutes  INTEGER NOT NULL DEFAULT 10 — interview duration in minutes (>= 1).
status            VARCHAR(20) NOT NULL DEFAULT 'Scheduled' — Enum: 'Scheduled', 'Completed', 'Cancelled', 'Missed'.
meeting_link      TEXT NULLABLE — optional video/meeting room link.
created_at        TIMESTAMPTZ NOT NULL — creation timestamp.
updated_at        TIMESTAMPTZ NOT NULL — last modification timestamp.

Constraints
-----------
CHECK (duration_minutes >= 1)

Relationships
-------------
interview.user → User (many-to-one, unidirectional)
interview.task → Task (many-to-one, unidirectional)

Registration
------------
Add the following line in ``app/db/base.py``::

    from app.models.interview import Interview  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.task import Task  # noqa: F401
    from app.models.user import User  # noqa: F401
    from app.models.interview_question import InterviewQuestion  # noqa: F401
    from app.models.interview_feedback import InterviewFeedback  # noqa: F401


class Interview(Base):
    """SQLAlchemy 2.x ORM model for the ``interviews`` table.

    Represents a scheduled mock interview session for a user based on their
    evaluated task performance.

    Attributes:
        id: UUID primary key, generated by Python before INSERT.
        user_id: FK to the scheduled ``User``.
        task_id: FK to the associated ``Task``.
        scheduled_at: UTC datetime of the interview start.
        duration_minutes: Duration in minutes (default 10).
        status: Interview status — ``'Scheduled'``, ``'Completed'``, ``'Cancelled'``, ``'Missed'``.
        meeting_link: Optional URL to meeting software or room.
        created_at: Creation timestamp.
        updated_at: Last modification timestamp.
        user: ORM relationship to the ``User``.
        task: ORM relationship to the ``Task``.
    """

    __tablename__ = "interviews"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        CheckConstraint(
            "duration_minutes >= 1",
            name="ck_interviews_duration_positive",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign keys ─────────────────────────────────────────────────────── #
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → users.id. Interview deleted when user is deleted.",
    )

    task_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tasks.id. Interview deleted when task is deleted.",
    )

    # ── Scheduling details ────────────────────────────────────────────────── #
    scheduled_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        comment="Scheduled start time in UTC.",
    )

    duration_minutes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=10,
        server_default="10",
        comment="Interview duration in minutes. Must be >= 1.",
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Scheduled",
        server_default="Scheduled",
        comment="Lifecycle status: 'Scheduled', 'Completed', 'Cancelled', 'Missed'.",
    )

    meeting_link: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional meeting link (e.g. video room URL).",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        lazy="select",
    )

    task: Mapped["Task"] = relationship(  # type: ignore[name-defined]
        "Task",
        lazy="select",
    )

    questions: Mapped[list["InterviewQuestion"]] = relationship(
        "InterviewQuestion",
        back_populates="interview",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="InterviewQuestion.order_no.asc()",
    )

    feedback: Mapped[Optional["InterviewFeedback"]] = relationship(
        "InterviewFeedback",
        back_populates="interview",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"Interview("
            f"id={self.id!r}, "
            f"user_id={self.user_id!r}, "
            f"task_id={self.task_id!r}, "
            f"status={self.status!r}, "
            f"scheduled_at={self.scheduled_at!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary."""
        return f"Interview {self.id} (user={self.user_id}, task={self.task_id}, status={self.status})"
