"""
backend/app/models/profession.py
----------------------------------
ORM model for the ``professions`` table.

Table overview
--------------
``professions`` stores career path metadata used to power the platform's
career-guidance features — roadmaps, skill-gap analysis, and AI interview
prep.  It is a **reference / catalogue** table: rows are created and managed
by admins; learners read from it.

Columns
-------
id              UUID PK — Python-generated (uuid4).
name            VARCHAR(255) UNIQUE NOT NULL — human display name.
slug            VARCHAR(255) UNIQUE NOT NULL — URL-safe identifier.
description     TEXT NULLABLE — rich Markdown description.
category        VARCHAR(100) NULLABLE — e.g. "Engineering", "Design".
average_salary  NUMERIC(12,2) NULLABLE — indicative annual salary (USD).
growth_rate     NUMERIC(5,2) NULLABLE — projected YoY growth percentage.
required_skills JSONB NOT NULL DEFAULT '[]' — ordered list of skill strings.
roadmap         JSONB NOT NULL DEFAULT '{}' — structured learning roadmap.
is_active       BOOLEAN NOT NULL DEFAULT true — soft-delete / hide flag.
created_at      TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at      TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Registration
------------
Uncomment the following line in ``app/db/base.py`` after creating this file::

    from app.models.profession import Profession  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Profession(Base):
    """SQLAlchemy 2.x ORM model for the ``professions`` table.

    Represents a career path on the platform.  Admins create and manage
    profession records; learners browse them to discover roadmaps, required
    skills, and salary benchmarks.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        name: Full human-readable profession name (e.g. "Machine Learning Engineer").
        slug: URL-safe lowercase identifier (e.g. "machine-learning-engineer").
            Used in API paths and canonical URLs.  Unique.
        description: Optional long-form Markdown description of the profession.
        category: Optional grouping category (e.g. "Engineering", "Design").
        average_salary: Indicative annual salary in USD, stored as NUMERIC
            with 2 decimal places.  ``None`` if unknown.
        growth_rate: Projected year-over-year growth rate (%) stored as
            NUMERIC(5,2).  E.g. ``12.50`` means 12.5%.  ``None`` if unknown.
        required_skills: Ordered JSON array of skill name strings.
            E.g. ``["Python", "ML Fundamentals", "PyTorch"]``.
        roadmap: Structured JSON object describing the learning roadmap.
            Schema is flexible; the service layer validates structure.
        is_active: ``True`` = profession is visible to learners.
            ``False`` = hidden / soft-deleted (preserved for FK integrity).
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
    """

    __tablename__ = "professions"

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Name ─────────────────────────────────────────────────────────────── #
    name: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="Human-readable profession name. Unique across the platform.",
    )

    # ── Slug ─────────────────────────────────────────────────────────────── #
    slug: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="URL-safe lowercase identifier. Unique. Used in API paths.",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional Markdown description of the profession.",
    )

    # ── Category ─────────────────────────────────────────────────────────── #
    category: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
        comment="Grouping category e.g. 'Engineering', 'Design', 'Data'.",
    )

    # ── Salary ───────────────────────────────────────────────────────────── #
    average_salary: Mapped[float | None] = mapped_column(
        Numeric(precision=12, scale=2),
        nullable=True,
        comment="Indicative annual salary in USD. NULL if unknown.",
    )

    # ── Growth rate ───────────────────────────────────────────────────────── #
    growth_rate: Mapped[float | None] = mapped_column(
        Numeric(precision=5, scale=2),
        nullable=True,
        comment="Projected YoY growth % e.g. 12.50 = 12.5%. NULL if unknown.",
    )

    # ── Required skills ───────────────────────────────────────────────────── #
    required_skills: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default="'[]'::jsonb",
        comment="Ordered JSON array of required skill strings.",
    )

    # ── Roadmap ───────────────────────────────────────────────────────────── #
    roadmap: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default="'{}'::jsonb",
        comment="Structured JSON learning roadmap. Schema defined by service layer.",
    )

    # ── Soft-delete flag ──────────────────────────────────────────────────── #
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        index=True,
        comment="False = hidden from learners. Prefer over hard DELETE.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log (no secrets)."""
        return (
            f"Profession("
            f"id={self.id!r}, "
            f"name={self.name!r}, "
            f"slug={self.slug!r}, "
            f"is_active={self.is_active!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable name — used in template rendering and f-string logs."""
        return self.name
