"""
backend/app/models/role.py
---------------------------
ORM model for the `roles` table.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WHAT THIS FILE DEFINES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • The `Role` ORM model (SQLAlchemy 2.x `DeclarativeBase` style).
  • Table: `roles`
  • Relationship: one Role → many Users  (back-populated on User.role)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COLUMN OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  id           UUID PRIMARY KEY — generated in Python (uuid4), so the PK is
               known before the INSERT reaches the database.

  name         VARCHAR(100) UNIQUE NOT NULL — short, human-readable role
               label (e.g. "admin", "learner", "mentor").

  description  TEXT NULLABLE — optional free-text explanation of the role's
               purpose.  TEXT instead of VARCHAR because descriptions have
               no meaningful maximum length.

  created_at   TIMESTAMP WITH TIME ZONE — set server-side by PostgreSQL at
               INSERT time via func.now(); never changes after creation.

  updated_at   TIMESTAMP WITH TIME ZONE — set server-side at INSERT and
               refreshed automatically on every UPDATE via onupdate hook.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DESIGN DECISIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  • UUID PK: avoids sequential ID enumeration attacks (security) and makes
    distributed ID generation safe (no auto-increment coordination needed).

  • Python-side UUID default (uuid.uuid4, not server_default):
    The PK is available in the Python object before the DB round-trip,
    which simplifies logging, unit testing, and relationship assignment.

  • TIMESTAMP WITH TIME ZONE: PostgreSQL stores UTC internally regardless
    of where the application is deployed.  Avoids the classic "it works
    in dev but breaks in prod" timezone bug.

  • `back_populates` instead of `backref`:
    Fully explicit bidirectional relationship declaration — both sides are
    visible to the type checker (mypy, pyright).  `backref` is a 1.x
    shortcut that hides the reverse side from static analysis.

  • `TYPE_CHECKING` guard on User import:
    Prevents the circular import that would occur at runtime if Role imports
    User and User imports Role.  The guard means the import only exists for
    the type checker, never at runtime.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REGISTRATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Add the following line to app/db/base.py to register this model with
  Base.metadata so Alembic autogenerate and create_all() can see it:

      from app.models.role import Role  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

# ── TYPE_CHECKING guard ───────────────────────────────────────────────────── #
# `User` is imported ONLY for static analysis (mypy / pyright / IDEs).
# At runtime this block is never executed, so there is no circular import
# between role.py ↔ user.py even when both declare a bidirectional relationship.
if TYPE_CHECKING:
    from app.models.user import User


# =========================================================================== #
#  Role ORM model                                                               #
# =========================================================================== #

class Role(Base):
    """
    Represents a user role in the system (e.g. ``admin``, ``learner``,
    ``mentor``).

    Each role may be assigned to many :class:`~app.models.user.User` instances.
    The ``users`` relationship gives a Role object direct access to all users
    that hold it, while ``User.role`` holds the reverse reference.

    Table
    -----
    ``roles``

    Relationships
    -------------
    users : list[User]
        All users currently assigned this role.
        Back-populated by ``User.role``.
    """

    __tablename__ = "roles"

    # ── Primary key ──────────────────────────────────────────────────────── #
    # UUID is generated by Python (uuid.uuid4) at object construction time,
    # NOT by the database.  This means:
    #   • The PK is available immediately after `Role(...)` — no DB round-trip.
    #   • Unit tests can assert on a known UUID without touching the DB.
    #   • Bulk inserts via `session.add_all(...)` never need a DB sequence.
    #
    # `UUID(as_uuid=True)` is the PostgreSQL-native UUID column type from
    # `sqlalchemy.dialects.postgresql`.  It stores UUIDs in PostgreSQL's
    # native 16-byte binary format (not as a 36-character string), which is
    # faster to index and compare than the VARCHAR representation.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,     # Python callable — invoked per row, not once.
        nullable=False,
        comment="Surrogate primary key.  Generated by Python (UUID v4).",
    )

    # ── Name ─────────────────────────────────────────────────────────────── #
    # VARCHAR(100) instead of TEXT because:
    #   • Role names are short identifiers, not paragraphs.
    #   • PostgreSQL can create more efficient B-tree index entries for
    #     VARCHAR(n) columns with known max length.
    #   • The DB enforces the length constraint even on bulk inserts that
    #     bypass Pydantic validation.
    #
    # UNIQUE constraint ensures no two roles share the same name.
    # The unique index created by PostgreSQL also speeds up lookups by name.
    name: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True,             # Explicit index for fast name lookups.
        comment="Human-readable role identifier (e.g. 'admin', 'learner').",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    # TEXT (unbounded) instead of VARCHAR because descriptions have no natural
    # maximum length.  Nullable because a description is optional metadata —
    # the role is fully functional without it.
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
        comment="Optional free-text description of the role's purpose and permissions.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    # Both columns use `TIMESTAMP WITH TIME ZONE` (mapped via timezone=True),
    # which tells PostgreSQL to store the value as UTC regardless of the DB
    # server's local timezone setting.  This is non-negotiable for any
    # application that may be deployed across multiple regions.
    #
    # `server_default=func.now()`:
    #   PostgreSQL evaluates this at INSERT time on the DB server.  Using a
    #   server_default rather than a Python `default=datetime.utcnow` means:
    #     • Bulk inserts via raw SQL still get a correct timestamp.
    #     • The value is correct even if the Python process clock drifts.
    #     • No timezone-naive datetime is ever generated in Python code.
    #
    # `onupdate=func.now()` (created_at only has server_default; updated_at
    # has both so it refreshes on every UPDATE statement touching the row).
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of when this row was first created.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),  # Set on INSERT (same as created_at).
        onupdate=func.now(),        # Refreshed automatically on every UPDATE.
        comment="UTC timestamp of the most recent modification to this row.",
    )

    # =========================================================================
    #  Relationships
    # =========================================================================

    # ── One Role → Many Users ─────────────────────────────────────────────── #
    # `back_populates="role"` declares the explicit reverse side of this
    # relationship — `User.role` must be declared on the User model with
    # `back_populates="users"` for SQLAlchemy to wire the bidirectional link.
    #
    # `lazy="select"` (default): users are loaded with a separate SELECT
    # when `role.users` is first accessed.  This is the safest default —
    # "eager" loading (joined/subquery) is opt-in at the query level via
    # `selectinload(Role.users)` when performance requires it.
    #
    # `cascade="all, delete-orphan"` is intentionally NOT set here:
    # deleting a Role should NOT cascade-delete Users — users should be
    # reassigned or blocked, not silently removed.  The FK constraint on
    # users.role_id will enforce referential integrity at the DB level.
    users: Mapped[list["User"]] = relationship(
        "User",
        back_populates="role",
        lazy="select",
        doc="All users assigned this role.",
    )

    # =========================================================================
    #  Dunder methods
    # =========================================================================

    def __repr__(self) -> str:
        """
        Unambiguous developer representation.

        Shown in debugger watches, log lines, and test assertion messages.
        Includes the class name, PK, and the most human-readable column so
        that log lines like ``Role(id=..., name='admin')`` are self-contained.
        """
        return (
            f"Role("
            f"id={self.id!r}, "
            f"name={self.name!r}"
            f")"
        )

    def __str__(self) -> str:
        """
        Human-readable string representation.

        Used when the object is coerced to ``str()`` — for example in
        template rendering, logging f-strings, or API response serialisation
        helpers that fall through to str().
        """
        return self.name
