"""
backend/app/models/user_progress.py
--------------------------------------
ORM model for the ``user_progress`` table.

Table overview
--------------
``user_progress`` tracks a learner's advancement through each skill on the
platform.  Every record ties exactly one ``User`` to exactly one ``Skill``
and carries the full progress state: status, percentage, time tracking, and
lifecycle timestamps.

One User can have many UserProgress records (one per Skill they have
engaged with).  One Skill can have many UserProgress records (one per User
who has engaged with it).

A UNIQUE constraint on ``(user_id, skill_id)`` enforces the invariant that
a user can only have **one** progress record per skill — duplicates are
prevented at the DB level.

Columns
-------
id                   UUID PK — Python-generated (uuid4).
user_id              UUID FK → users.id NOT NULL — learner tracking this progress.
skill_id             UUID FK → skills.id NOT NULL — skill being learned.
status               VARCHAR(20) NOT NULL — Enum: NOT_STARTED, IN_PROGRESS, COMPLETED.
progress_percentage  INTEGER NOT NULL DEFAULT 0 — 0 to 100 inclusive.
started_at           TIMESTAMPTZ NULLABLE — when the user first began the skill.
completed_at         TIMESTAMPTZ NULLABLE — when progress_percentage reached 100.
last_accessed        TIMESTAMPTZ NULLABLE — most recent interaction timestamp.
time_spent_minutes   INTEGER NOT NULL DEFAULT 0 — cumulative time spent (>= 0).
created_at           TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at           TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Constraints
-----------
UNIQUE (user_id, skill_id) — one progress record per user per skill.
CHECK  (progress_percentage BETWEEN 0 AND 100) — enforced at DB level.
CHECK  (time_spent_minutes >= 0) — cumulative time cannot be negative.

Relationships
-------------
user_progress.user  → User   (many-to-one, ``back_populates=\"progress_records\"``)
user_progress.skill → Skill  (many-to-one, ``back_populates=\"user_progress_records\"``)

Registration
------------
Add the following line in ``app/db/base.py`` after creating this file::

    from app.models.user_progress import UserProgress  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class UserProgress(Base):
    """SQLAlchemy 2.x ORM model for the ``user_progress`` table.

    Represents a single learner's progress state for one skill.  One
    ``User`` can have many ``UserProgress`` records; one ``Skill`` can
    have many ``UserProgress`` records (many-to-many with extra payload).

    The UNIQUE constraint on ``(user_id, skill_id)`` prevents duplicate
    progress rows at the database level.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        user_id: FK to the ``User`` whose progress this tracks.
        skill_id: FK to the ``Skill`` being learned.
        status: Lifecycle status — one of ``'NOT_STARTED'``,
            ``'IN_PROGRESS'``, or ``'COMPLETED'``.
        progress_percentage: Integer 0–100 representing completion.
        started_at: UTC timestamp of the learner's first interaction.
            ``None`` until the learner begins.
        completed_at: UTC timestamp when the skill was completed (100%).
            ``None`` until completion.
        last_accessed: UTC timestamp of the most recent interaction.
            ``None`` until first access.
        time_spent_minutes: Cumulative minutes spent on this skill.
            Must be >= 0.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        user: ORM relationship to the learner ``User`` instance.
        skill: ORM relationship to the ``Skill`` instance.
    """

    __tablename__ = "user_progress"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "skill_id",
            name="uq_user_progress_user_skill",
        ),
        CheckConstraint(
            "progress_percentage BETWEEN 0 AND 100",
            name="ck_user_progress_percentage_range",
        ),
        CheckConstraint(
            "time_spent_minutes >= 0",
            name="ck_user_progress_time_non_negative",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — User ───────────────────────────────────────────────── #
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → users.id. Progress is deleted when the user is deleted.",
    )

    # ── Foreign key — Skill ──────────────────────────────────────────────── #
    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("skills.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → skills.id. Progress is deleted when the skill is deleted.",
    )

    # ── Status ───────────────────────────────────────────────────────────── #
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="NOT_STARTED",
        server_default="'NOT_STARTED'",
        index=True,
        comment="Lifecycle status: 'NOT_STARTED', 'IN_PROGRESS', or 'COMPLETED'.",
    )

    # ── Progress percentage ───────────────────────────────────────────────── #
    progress_percentage: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Completion percentage 0–100. Enforced by CHECK constraint.",
    )

    # ── Started at ───────────────────────────────────────────────────────── #
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp of the learner's first interaction. NULL until begun.",
    )

    # ── Completed at ─────────────────────────────────────────────────────── #
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the skill was marked completed. NULL until done.",
    )

    # ── Last accessed ────────────────────────────────────────────────────── #
    last_accessed: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp of the most recent interaction. NULL until first access.",
    )

    # ── Time spent ───────────────────────────────────────────────────────── #
    time_spent_minutes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Cumulative minutes spent learning this skill. Must be >= 0.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        back_populates="progress_records",
        lazy="select",
    )

    skill: Mapped["Skill"] = relationship(  # type: ignore[name-defined]
        "Skill",
        back_populates="user_progress_records",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log (no secrets)."""
        return (
            f"UserProgress("
            f"id={self.id!r}, "
            f"user_id={self.user_id!r}, "
            f"skill_id={self.skill_id!r}, "
            f"status={self.status!r}, "
            f"progress_percentage={self.progress_percentage!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary — used in f-string logs."""
        return (
            f"UserProgress(user={self.user_id}, "
            f"skill={self.skill_id}, "
            f"{self.progress_percentage}% {self.status})"
        )
