/**
 * Complete catalog of professional career paths in tech.
 * Includes all required professions with detailed descriptions, skills,
 * duration, difficulty, category, salary, and growth metrics.
 */

export const PROFESSION_CATALOG = [
  {
    id: 'ai-engineer',
    slug: 'ai-engineer',
    title: 'AI Engineer',
    name: 'AI Engineer',
    category: 'AI & Machine Learning',
    description: 'Design, build, and deploy generative AI applications, LLM pipelines, neural networks, and scalable AI infrastructure.',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'FastAPI', 'Docker', 'Git', 'Linux'],
    estimatedDuration: '16 Weeks',
    difficulty: 'Advanced',
    averageSalary: '$135,000 - $185,000',
    growthRate: '+38% annual growth',
    badgeColor: '#6366f1',
    icon: 'Brain',
  },
  {
    id: 'ml-engineer',
    slug: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    name: 'Machine Learning Engineer',
    category: 'AI & Machine Learning',
    description: 'Develop predictive models, feature pipelines, recommendation engines, and end-to-end MLOps production systems.',
    skills: ['Python', 'Scikit-learn', 'PyTorch', 'Pandas', 'NumPy', 'Docker', 'SQL'],
    estimatedDuration: '16 Weeks',
    difficulty: 'Advanced',
    averageSalary: '$130,000 - $175,000',
    growthRate: '+32% annual growth',
    badgeColor: '#8b5cf6',
    icon: 'Cpu',
  },
  {
    id: 'data-scientist',
    slug: 'data-scientist',
    title: 'Data Scientist',
    name: 'Data Scientist',
    category: 'Data & Analytics',
    description: 'Extract statistical insights, perform predictive modeling, design experiments, and communicate data-driven strategy.',
    skills: ['Python', 'SQL', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'Git'],
    estimatedDuration: '14 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$120,000 - $160,000',
    growthRate: '+26% annual growth',
    badgeColor: '#06b6d4',
    icon: 'LineChart',
  },
  {
    id: 'data-analyst',
    slug: 'data-analyst',
    title: 'Data Analyst',
    name: 'Data Analyst',
    category: 'Data & Analytics',
    description: 'Transform complex business datasets into actionable dashboards, SQL queries, and strategic decision frameworks.',
    skills: ['SQL', 'Python', 'Pandas', 'NumPy', 'Git'],
    estimatedDuration: '10 Weeks',
    difficulty: 'Beginner',
    averageSalary: '$85,000 - $115,000',
    growthRate: '+22% annual growth',
    badgeColor: '#3b82f6',
    icon: 'BarChart2',
  },
  {
    id: 'backend-developer',
    slug: 'backend-developer',
    title: 'Backend Developer',
    name: 'Backend Developer',
    category: 'Software Engineering',
    description: 'Engineer high-throughput REST & GraphQL APIs, microservices architectures, databases, and secure auth pipelines.',
    skills: ['Node.js', 'FastAPI', 'Python', 'Java', 'SQL', 'Docker', 'Git', 'Linux'],
    estimatedDuration: '14 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$110,000 - $150,000',
    growthRate: '+18% annual growth',
    badgeColor: '#10b981',
    icon: 'Server',
  },
  {
    id: 'frontend-developer',
    slug: 'frontend-developer',
    title: 'Frontend Developer',
    name: 'Frontend Developer',
    category: 'Software Engineering',
    description: 'Build responsive, accessible, interactive web interfaces using React, JavaScript, modern CSS, and component systems.',
    skills: ['JavaScript', 'React', 'Git', 'Node.js'],
    estimatedDuration: '12 Weeks',
    difficulty: 'Beginner',
    averageSalary: '$100,000 - $140,000',
    growthRate: '+20% annual growth',
    badgeColor: '#ec4899',
    icon: 'Layout',
  },
  {
    id: 'fullstack-developer',
    slug: 'full-stack-developer',
    title: 'Full Stack Developer',
    name: 'Full Stack Developer',
    category: 'Software Engineering',
    description: 'Master complete web application lifecycles from interactive frontends to robust backend microservices and databases.',
    skills: ['React', 'Node.js', 'JavaScript', 'FastAPI', 'SQL', 'Git', 'Docker'],
    estimatedDuration: '18 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$120,000 - $165,000',
    growthRate: '+24% annual growth',
    badgeColor: '#a855f7',
    icon: 'Layers',
  },
  {
    id: 'devops-engineer',
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    name: 'DevOps Engineer',
    category: 'Cloud & Infrastructure',
    description: 'Automate CI/CD build pipelines, infrastructure-as-code deployments, Kubernetes orchestration, and monitoring systems.',
    skills: ['Docker', 'Linux', 'AWS', 'Azure', 'Git', 'Python'],
    estimatedDuration: '14 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$125,000 - $170,000',
    growthRate: '+28% annual growth',
    badgeColor: '#f59e0b',
    icon: 'GitBranch',
  },
  {
    id: 'cloud-engineer',
    slug: 'cloud-engineer',
    title: 'Cloud Engineer',
    name: 'Cloud Engineer',
    category: 'Cloud & Infrastructure',
    description: 'Architect multi-cloud solutions, serverless functions, cloud security policies, and high-availability networking.',
    skills: ['AWS', 'Azure', 'Linux', 'Docker', 'Python', 'SQL'],
    estimatedDuration: '14 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$125,000 - $168,000',
    growthRate: '+27% annual growth',
    badgeColor: '#0284c7',
    icon: 'Cloud',
  },
  {
    id: 'cyber-security-engineer',
    slug: 'cyber-security-engineer',
    title: 'Cyber Security Engineer',
    name: 'Cyber Security Engineer',
    category: 'Security & Systems',
    description: 'Protect application infrastructures, perform vulnerability assessments, encrypt network traffic, and conduct threat analysis.',
    skills: ['Linux', 'Python', 'Git', 'Docker', 'AWS'],
    estimatedDuration: '16 Weeks',
    difficulty: 'Advanced',
    averageSalary: '$130,000 - $175,000',
    growthRate: '+31% annual growth',
    badgeColor: '#ef4444',
    icon: 'ShieldAlert',
  },
  {
    id: 'android-developer',
    slug: 'android-developer',
    title: 'Android Developer',
    name: 'Android Developer',
    category: 'Mobile Development',
    description: 'Craft native mobile applications for Android, optimized UI components, local storage, and cloud synchronization.',
    skills: ['Java', 'C++', 'Git', 'React'],
    estimatedDuration: '14 Weeks',
    difficulty: 'Intermediate',
    averageSalary: '$105,000 - $145,000',
    growthRate: '+19% annual growth',
    badgeColor: '#22c55e',
    icon: 'Smartphone',
  },
  {
    id: 'ui-ux-designer',
    slug: 'ui-ux-designer',
    title: 'UI/UX Designer',
    name: 'UI/UX Designer',
    category: 'Design & Product',
    description: 'Design intuitive wireframes, user journeys, visual design systems, interactive prototypes, and usability testing.',
    skills: ['React', 'JavaScript'],
    estimatedDuration: '10 Weeks',
    difficulty: 'Beginner',
    averageSalary: '$95,000 - $135,000',
    growthRate: '+18% annual growth',
    badgeColor: '#f43f5e',
    icon: 'Figma',
  },
  {
    id: 'qa-engineer',
    slug: 'qa-engineer',
    title: 'QA Engineer',
    name: 'QA Engineer',
    category: 'Software Engineering',
    description: 'Build automated E2E testing suites, integration tests, performance benchmarking, and continuous quality audits.',
    skills: ['Python', 'JavaScript', 'Git', 'SQL', 'Docker'],
    estimatedDuration: '10 Weeks',
    difficulty: 'Beginner',
    averageSalary: '$85,000 - $120,000',
    growthRate: '+16% annual growth',
    badgeColor: '#14b8a6',
    icon: 'CheckSquare',
  },
  {
    id: 'blockchain-developer',
    slug: 'blockchain-developer',
    title: 'Blockchain Developer',
    name: 'Blockchain Developer',
    category: 'Web3 & Security',
    description: 'Engineer decentralized smart contracts, Web3 dApps, consensus protocol integrations, and cryptographic security.',
    skills: ['JavaScript', 'C++', 'Node.js', 'Python', 'Git', 'Docker'],
    estimatedDuration: '16 Weeks',
    difficulty: 'Advanced',
    averageSalary: '$135,000 - $190,000',
    growthRate: '+25% annual growth',
    badgeColor: '#84cc16',
    icon: 'Boxes',
  },
];

export const SKILL_OPTIONS = [
  'Python',
  'Java',
  'C++',
  'JavaScript',
  'React',
  'Node.js',
  'FastAPI',
  'SQL',
  'Git',
  'Linux',
  'Docker',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Scikit-learn',
  'AWS',
  'Azure',
];

export const INTEREST_OPTIONS = [
  { label: 'AI', icon: 'Sparkles', desc: 'Neural Networks, LLMs & Machine Intelligence' },
  { label: 'Web Development', icon: 'Code', desc: 'Modern Web Apps & Scalable Interfaces' },
  { label: 'Data Science', icon: 'Database', desc: 'Big Data Analysis, Statistics & Insights' },
  { label: 'Cyber Security', icon: 'Shield', desc: 'Network Defense, Encryption & Ethical Hacking' },
  { label: 'Competitive Programming', icon: 'Terminal', desc: 'Algorithms, Data Structures & Logic' },
  { label: 'Cloud', icon: 'Cloud', desc: 'Serverless Infrastructure & Global Systems' },
  { label: 'Blockchain', icon: 'Boxes', desc: 'Smart Contracts, Web3 & Cryptography' },
  { label: 'Game Development', icon: 'Gamepad2', desc: '3D Graphics, Game Engines & Physics' },
];

export const GOAL_PROFESSION_OPTIONS = [
  'AI Engineer',
  'Machine Learning Engineer',
  'Data Scientist',
  'Data Analyst',
  'Backend Developer',
  'Frontend Developer',
  'Full Stack Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Cyber Security Engineer',
  'Android Developer',
  'UI/UX Designer',
  'QA Engineer',
  'Blockchain Developer',
];

export const ASSESSMENT_QUESTIONS = [
  {
    id: 1,
    question: 'Which area of problem-solving excites you the most?',
    options: [
      { text: 'Building intelligent algorithms that learn from data and automate decision-making', alignment: ['AI Engineer', 'Machine Learning Engineer', 'Data Scientist'] },
      { text: 'Engineering robust server APIs, microservices, and reliable database architectures', alignment: ['Backend Developer', 'DevOps Engineer', 'Cloud Engineer'] },
      { text: 'Crafting responsive, high-impact web interfaces with slick interactive user experiences', alignment: ['Frontend Developer', 'Full Stack Developer', 'UI/UX Designer'] },
      { text: 'Securing cloud systems, analyzing system vulnerabilities, or building decentralized networks', alignment: ['Cyber Security Engineer', 'Blockchain Developer'] },
    ],
  },
  {
    id: 2,
    question: 'What is your ideal project artifact?',
    options: [
      { text: 'A trained AI model or predictive dashboard delivering business predictions', alignment: ['AI Engineer', 'Machine Learning Engineer', 'Data Analyst'] },
      { text: 'A high-throughput API microservice serving millions of user requests', alignment: ['Backend Developer', 'Full Stack Developer', 'DevOps Engineer'] },
      { text: 'A production web app, mobile application, or interactive user interface', alignment: ['Frontend Developer', 'Android Developer', 'UI/UX Designer'] },
      { text: 'An automated CI/CD cloud pipeline or hardened secure infrastructure', alignment: ['DevOps Engineer', 'Cloud Engineer', 'Cyber Security Engineer', 'QA Engineer'] },
    ],
  },
  {
    id: 3,
    question: 'How do you prefer working with technology?',
    options: [
      { text: 'Experimental & Research-driven — working with python libraries, datasets & models', alignment: ['Data Scientist', 'AI Engineer', 'Machine Learning Engineer'] },
      { text: 'Systematic & Architectural — working with databases, server code & backend logic', alignment: ['Backend Developer', 'Full Stack Developer', 'Cloud Engineer'] },
      { text: 'Visual & User-centric — focusing on component styling, usability & frontend code', alignment: ['Frontend Developer', 'UI/UX Designer', 'Android Developer'] },
      { text: 'Quality & Security-oriented — testing edge cases, stress tests & system defenses', alignment: ['QA Engineer', 'Cyber Security Engineer', 'DevOps Engineer'] },
    ],
  },
  {
    id: 4,
    question: 'What type of daily coding activity sounds most rewarding to you?',
    options: [
      { text: 'Optimizing model hyper-parameters or running data transformations in Jupyter/Pandas', alignment: ['Machine Learning Engineer', 'Data Scientist', 'Data Analyst'] },
      { text: 'Writing clean API routes, SQL queries, and handling async database connections', alignment: ['Backend Developer', 'Full Stack Developer'] },
      { text: 'Creating reusable React components, state hooks, and UI micro-animations', alignment: ['Frontend Developer', 'Full Stack Developer'] },
      { text: 'Writing bash scripts, Dockerfiles, Terraform configs, or security audit tools', alignment: ['DevOps Engineer', 'Cloud Engineer', 'Cyber Security Engineer'] },
    ],
  },
];
