"""add_learning_paths_table

Revision ID: 2f007cd42e20
Revises:     10b63635f9c7
Create Date: 2026-07-25 23:38:45.324583

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MIGRATION NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Add a plain-English description of WHAT this migration changes and WHY.
• If this migration is destructive (drops columns / tables), note what data
  is at risk and confirm the downgrade() restores the previous state.
• Link the GitHub issue or PR that prompted this change, e.g.:
    Ref: https://github.com/Kartikpatidar0006/AI-Powerd-Career-Learning-Plateform/issues/123
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ---------------------------------------------------------------------------
# Revision identifiers — managed by Alembic, do not edit manually.
# ---------------------------------------------------------------------------
revision: str = '2f007cd42e20'
down_revision: Union[str, Sequence[str], None] = '10b63635f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('profession_id', sa.UUID(), nullable=False, comment='FK → professions.id. Entry is removed when the profession is deleted.'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK → skills.id. Entry is removed when the skill is deleted.'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='1-based step number within the profession path. Unique per profession.'),
    sa.Column('estimated_weeks', sa.Integer(), server_default='1', nullable=False, comment='Expected number of weeks to complete this step. Must be >= 1.'),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False, comment='True = mandatory for path completion. False = optional enrichment.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profession_id', 'sequence', name='uq_learning_paths_profession_sequence'),
    sa.UniqueConstraint('profession_id', 'skill_id', name='uq_learning_paths_profession_skill')
    )
    op.create_index(op.f('ix_learning_paths_is_required'), 'learning_paths', ['is_required'], unique=False)
    op.create_index(op.f('ix_learning_paths_profession_id'), 'learning_paths', ['profession_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_sequence'), 'learning_paths', ['sequence'], unique=False)
    op.create_index(op.f('ix_learning_paths_skill_id'), 'learning_paths', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_paths_skill_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_sequence'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_profession_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_is_required'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
