"""add_skills_table

Revision ID: 10b63635f9c7
Revises:     a1b2c3d4e5f6
Create Date: 2026-07-25 23:29:17.154995

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MIGRATION NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Add a plain-English description of WHAT this migration changes and WHY.
• If this migration is destructive (drops columns / tables), note what data
  is at risk and confirm the downgrade() restores the previous state.
• Link the GitHub issue or PR that prompted this change, e.g.:
    Ref: https://github.com/Kartikpatidar0006/AI-Powerd-Career-Learning-Plateform/issues/123
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ---------------------------------------------------------------------------
# Revision identifiers — managed by Alembic, do not edit manually.
# ---------------------------------------------------------------------------
revision: str = '10b63635f9c7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key.  Generated by Python (UUID v4).'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable role identifier (e.g. 'admin', 'learner')."),
    sa.Column('description', sa.Text(), nullable=True, comment="Optional free-text description of the role's purpose and permissions."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of when this row was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the most recent modification to this row.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable skill name (e.g. 'Python', 'Data Structures')."),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional Markdown description of the skill.'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'."),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Grouping category e.g. 'Programming', 'Soft Skills', 'DevOps'."),
    sa.Column('profession_id', sa.UUID(), nullable=False, comment='FK → professions.id.  Skill is deleted when Profession is hard-deleted.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_difficulty'), 'skills', ['difficulty'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_skills_profession_id'), 'skills', ['profession_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key.  Generated by Python (UUID v4).'),
    sa.Column('role_id', sa.UUID(), nullable=True, comment='FK → roles.id.  NULL means no role assigned yet.  SET NULL on role deletion.'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name.  Not unique — two users may share a name."),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login identifier.  RFC 5321 max 254 chars.  Unique across the entire platform.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment="bcrypt/argon2 hash of the user's password.  NEVER stores plaintext.  Hashing is performed in app/core/security.py."),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = account suspended.  Prefer over hard-deleting user rows.'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='True once the user has confirmed their email address.  Unverified users may have restricted access depending on policy.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of account creation.  Immutable after INSERT.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the last modification to this user row.'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_constraint(op.f('uq_professions_name'), 'professions', type_='unique')
    op.drop_constraint(op.f('uq_professions_slug'), 'professions', type_='unique')
    op.drop_index(op.f('ix_professions_name'), table_name='professions')
    op.create_index(op.f('ix_professions_name'), 'professions', ['name'], unique=True)
    op.drop_index(op.f('ix_professions_slug'), table_name='professions')
    op.create_index(op.f('ix_professions_slug'), 'professions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professions_slug'), table_name='professions')
    op.create_index(op.f('ix_professions_slug'), 'professions', ['slug'], unique=False)
    op.drop_index(op.f('ix_professions_name'), table_name='professions')
    op.create_index(op.f('ix_professions_name'), 'professions', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_professions_slug'), 'professions', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_professions_name'), 'professions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_profession_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_difficulty'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
