"""create professions table

Revision ID: a1b2c3d4e5f6
Revises:     None
Create Date: 2026-07-23 10:12:00.000000

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MIGRATION NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is the **initial** migration for the ``professions`` table.

What this migration does (upgrade)
-----------------------------------
  • Creates the ``professions`` table with all 12 columns:
      id, name, slug, description, category, average_salary, growth_rate,
      required_skills, roadmap, is_active, created_at, updated_at.

  • Primary key:
      ``id`` — UUID v4, Python-generated before INSERT.

  • Named UNIQUE constraints (each also creates an implicit B-tree index):
      ``uq_professions_name``  — name must be globally unique.
      ``uq_professions_slug``  — slug must be globally unique.

  • Explicit B-tree indexes:
      ``ix_professions_name``      — fast ORDER BY / prefix search on name.
      ``ix_professions_slug``      — fast slug look-ups for canonical URLs.
      ``ix_professions_category``  — fast filter by category.
      ``ix_professions_is_active`` — critical: every listing query filters active.

  • Server-side defaults (evaluated by PostgreSQL at INSERT):
      required_skills  DEFAULT '[]'::jsonb
      roadmap          DEFAULT '{}'::jsonb
      is_active        DEFAULT true
      created_at       DEFAULT now()
      updated_at       DEFAULT now()

  • Column comments visible in psql \\d+ and pgAdmin.

What this migration does (downgrade)
--------------------------------------
  • Drops all explicit indexes created by upgrade().
  • Drops the ``professions`` table with CASCADE.

  ⚠  downgrade() is DESTRUCTIVE — all profession data will be permanently
     deleted.  Only run in development or after a confirmed data backup.

Ref: https://github.com/Kartikpatidar0006/AI-Powerd-Career-Learning-Plateform
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# ---------------------------------------------------------------------------
# Revision identifiers — managed by Alembic, do not edit manually.
# ---------------------------------------------------------------------------
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = None  # First migration — no parent.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ===========================================================================
#  upgrade — apply schema changes
# ===========================================================================

def upgrade() -> None:
    """Create the ``professions`` table with all columns, constraints, and indexes.

    Execution order
    ---------------
    1. ``op.create_table`` — creates the table including inline PK,
       NOT NULL, server-side DEFAULT definitions, and named UNIQUE constraints.
    2. ``op.create_index`` calls — create the explicit B-tree indexes that
       complement the implicit indexes built by the UNIQUE constraints.

    Design notes
    ------------
    * Named constraints (``uq_professions_name``, ``uq_professions_slug``)
      make PostgreSQL error messages, monitoring alerts, and future
      ``DROP CONSTRAINT`` statements unambiguous.
    * ``sa.text(...)`` wraps server defaults so they are rendered as raw
      SQL expressions rather than string literals — correct for PostgreSQL
      functions like ``now()`` and cast expressions like ``'[]'::jsonb``.
    * ``postgresql.JSONB`` is used instead of the generic ``sa.JSON`` to
      take advantage of PostgreSQL's binary JSONB storage, GIN indexing
      capability, and containment operators (``@>``, ``<@``).
    """

    # ── 1. Create table ──────────────────────────────────────────────────── #
    op.create_table(
        "professions",

        # ── Primary key ──────────────────────────────────────────────────── #
        # UUID v4, generated by Python before INSERT.  PostgreSQL stores UUIDs
        # in a compact 16-byte binary form; the UUID dialect type handles
        # serialisation transparently.
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            comment="Surrogate primary key — UUID v4 generated by Python.",
        ),

        # ── Name ─────────────────────────────────────────────────────────── #
        # VARCHAR(255) safely covers the longest realistic profession name
        # (RFC 5321 email max is 254; 255 is the universal VARCHAR sweet-spot).
        # The UNIQUE constraint on this column is declared below via
        # sa.UniqueConstraint so it receives an explicit name.
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable profession name. Unique across the platform.",
        ),

        # ── Slug ─────────────────────────────────────────────────────────── #
        # URL-safe lowercase identifier used in API paths and canonical URLs.
        # Normalised to ^[a-z0-9]+(?:-[a-z0-9]+)*$ by the Pydantic schema.
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-safe lowercase identifier. Unique. Used in API paths.",
        ),

        # ── Description ──────────────────────────────────────────────────── #
        # TEXT (unbounded) — long-form Markdown content.
        # Nullable: many professions may be created without a full description.
        # PostgreSQL stores TEXT inline (no TOAST overhead for short values)
        # and out-of-line via TOAST for values > 8 kB.
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional Markdown description of the profession.",
        ),

        # ── Category ─────────────────────────────────────────────────────── #
        # Short grouping tag (e.g. "Engineering", "Design", "Data Science").
        # VARCHAR(100) is sufficient; categories should be short, controlled
        # vocabularies rather than free-form text.
        # Nullable: a profession may not yet have a category assigned.
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=True,
            comment="Grouping category e.g. 'Engineering', 'Design', 'Data'.",
        ),

        # ── Average salary ───────────────────────────────────────────────── #
        # NUMERIC(12, 2): 10 integer digits + 2 decimal places.
        # Chosen over FLOAT to avoid IEEE-754 binary rounding artefacts —
        # NUMERIC stores exact decimal values, critical for financial figures.
        # precision=12 supports salaries up to 9,999,999,999.99 USD.
        # NULL = salary is unknown or not yet researched.
        sa.Column(
            "average_salary",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Indicative annual salary in USD. NULL if unknown.",
        ),

        # ── Growth rate ───────────────────────────────────────────────────── #
        # NUMERIC(5, 2): e.g. 12.50 means 12.5% year-over-year growth.
        # Range: -100.00 to 999.99 (enforced by Pydantic, not the DB).
        # NULL = growth rate is unknown.
        sa.Column(
            "growth_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Projected YoY growth % e.g. 12.50 = 12.5%. NULL if unknown.",
        ),

        # ── Required skills ───────────────────────────────────────────────── #
        # JSONB: binary JSON with O(1) key look-ups and GIN index support.
        # Stores an ordered array of skill name strings:
        #     ["Python", "Machine Learning", "PyTorch"]
        # server_default: PostgreSQL evaluates '[]'::jsonb at INSERT time,
        # ensuring correct defaults even for bulk inserts that bypass Python.
        sa.Column(
            "required_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
            comment="Ordered JSON array of required skill strings.",
        ),

        # ── Roadmap ───────────────────────────────────────────────────────── #
        # JSONB: flexible structured object describing the learning roadmap.
        # Schema is intentionally open — the service layer validates structure.
        # server_default: '{}'::jsonb ensures an empty object, not NULL.
        sa.Column(
            "roadmap",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
            comment="Structured JSON learning roadmap. Schema defined by service layer.",
        ),

        # ── Soft-delete / visibility flag ─────────────────────────────────── #
        # True (default) = profession is visible to learners.
        # False = hidden / soft-deleted (row preserved for referential integrity).
        # Prefer soft-delete over hard DELETE: other tables may FK to professions.
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="False = hidden from learners. Prefer over hard DELETE.",
        ),

        # ── created_at ────────────────────────────────────────────────────── #
        # TIMESTAMP WITH TIME ZONE: PostgreSQL stores UTC internally regardless
        # of the server's local timezone.  server_default=now() is evaluated
        # once at INSERT; the ORM model does NOT set onupdate here, making
        # this column effectively immutable after row creation.
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="UTC timestamp of row creation. Immutable.",
        ),

        # ── updated_at ────────────────────────────────────────────────────── #
        # server_default=now() sets the value at INSERT.
        # The ORM model's `onupdate=func.now()` refreshes it on every UPDATE
        # via the application layer.  A DB-level trigger could also handle
        # this, but the ORM approach is simpler and sufficient for production.
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
            comment="UTC timestamp of last modification. Auto-updated.",
        ),

        # ── Named UNIQUE constraints ──────────────────────────────────────── #
        # Named constraints appear in psql error messages and allow precise
        # DROP CONSTRAINT in future migrations without relying on
        # auto-generated names that may vary between databases.
        sa.UniqueConstraint("name", name="uq_professions_name"),
        sa.UniqueConstraint("slug", name="uq_professions_slug"),
    )

    # ── 2. Create explicit B-tree indexes ────────────────────────────────── #
    # These are separate from the implicit indexes created by UNIQUE constraints.
    # Explicit op.create_index entries survive alembic downgrade cleanly —
    # Alembic tracks them independently of the constraint-level indexes.

    # Supports: ORDER BY name ASC in list views; LIKE 'Eng%' prefix searches.
    op.create_index(
        index_name="ix_professions_name",
        table_name="professions",
        columns=["name"],
        unique=False,  # Uniqueness is already enforced by uq_professions_name.
    )

    # Supports: WHERE slug = 'machine-learning-engineer' (single-row look-up).
    op.create_index(
        index_name="ix_professions_slug",
        table_name="professions",
        columns=["slug"],
        unique=False,  # Uniqueness is already enforced by uq_professions_slug.
    )

    # Supports: WHERE category = 'Engineering' (common list-view filter).
    op.create_index(
        index_name="ix_professions_category",
        table_name="professions",
        columns=["category"],
        unique=False,
    )

    # Supports: WHERE is_active = true (every listing query uses this filter).
    # Without this index, every list call performs a full table scan.
    op.create_index(
        index_name="ix_professions_is_active",
        table_name="professions",
        columns=["is_active"],
        unique=False,
    )


# ===========================================================================
#  downgrade — revert schema changes
# ===========================================================================

def downgrade() -> None:
    """Drop all indexes and the ``professions`` table.

    Reversal order
    --------------
    Indexes MUST be dropped before the table — dropping the table first
    with CASCADE would silently remove them, but explicit removal keeps
    the downgrade transparent and avoids accidental cascade side-effects
    on other objects that may share index names in the schema.

    1. Drop explicit B-tree indexes (reverse order of upgrade step 2).
    2. Drop the table — CASCADE removes the implicit unique-constraint
       indexes (``uq_professions_name``, ``uq_professions_slug``) and
       any other dependent objects automatically.

    ⚠  WARNING
    -----------
    This operation is DESTRUCTIVE and IRREVERSIBLE in production.
    All rows in the ``professions`` table will be permanently deleted.
    Confirm a database backup exists before running downgrade in any
    environment that holds data you care about.
    """

    # ── 1. Drop explicit B-tree indexes ──────────────────────────────────── #
    op.drop_index("ix_professions_is_active", table_name="professions")
    op.drop_index("ix_professions_category",  table_name="professions")
    op.drop_index("ix_professions_slug",       table_name="professions")
    op.drop_index("ix_professions_name",       table_name="professions")

    # ── 2. Drop the table ─────────────────────────────────────────────────── #
    # CASCADE drops any remaining dependent objects (implicit constraint indexes,
    # sequences, FK constraints from child tables if any exist).
    op.drop_table("professions")
