"""Add notifications table and extend user_progress columns

Revision ID: 5bfe23a3c5b8
Revises:     6a28bd8529ce
Create Date: 2026-07-30 23:45:45.500927

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MIGRATION NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Add a plain-English description of WHAT this migration changes and WHY.
• If this migration is destructive (drops columns / tables), note what data
  is at risk and confirm the downgrade() restores the previous state.
• Link the GitHub issue or PR that prompted this change, e.g.:
    Ref: https://github.com/Kartikpatidar0006/AI-Powerd-Career-Learning-Plateform/issues/123
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# ---------------------------------------------------------------------------
# Revision identifiers — managed by Alembic, do not edit manually.
# ---------------------------------------------------------------------------
revision: str = '5bfe23a3c5b8'
down_revision: Union[str, Sequence[str], None] = '6a28bd8529ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roadmaps',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('profession_id', sa.UUID(), nullable=False, comment='FK → professions.id. Roadmap is deleted when Profession is deleted.'),
    sa.Column('title', sa.String(length=500), nullable=False, comment="Human-readable roadmap title (e.g. 'Full-Stack Developer Path')."),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional Markdown description of the roadmap.'),
    sa.Column('estimated_months', sa.Integer(), server_default='1', nullable=False, comment='Estimated calendar months to complete the full roadmap. Must be >= 1.'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'."),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = hidden from learners. Prefer over hard DELETE.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roadmaps_difficulty'), 'career_roadmaps', ['difficulty'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_is_active'), 'career_roadmaps', ['is_active'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_profession_id'), 'career_roadmaps', ['profession_id'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_title'), 'career_roadmaps', ['title'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('title', sa.String(length=500), nullable=False, comment="Human-readable course title (e.g. 'Python for Everybody')."),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional Markdown description of the course.'),
    sa.Column('provider', sa.String(length=255), nullable=True, comment="Publishing platform or instructor (e.g. 'Coursera', 'Udemy')."),
    sa.Column('course_url', sa.Text(), nullable=False, comment='Canonical URL to the course page. Required.'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='URL to the course cover image / thumbnail. Optional.'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'."),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=2), nullable=True, comment='Estimated hours to complete the course. NULL if unknown.'),
    sa.Column('is_free', sa.Boolean(), server_default='false', nullable=False, comment='True = course is available free of charge.'),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True, comment='Average community rating on a 0.00–5.00 scale. NULL if unrated.'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK → skills.id. Course is deleted when the Skill is hard-deleted.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_difficulty'), 'courses', ['difficulty'], unique=False)
    op.create_index(op.f('ix_courses_is_free'), 'courses', ['is_free'], unique=False)
    op.create_index(op.f('ix_courses_provider'), 'courses', ['provider'], unique=False)
    op.create_index(op.f('ix_courses_skill_id'), 'courses', ['skill_id'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id. Deleted when user is deleted.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Notification headline / title.'),
    sa.Column('message', sa.Text(), nullable=False, comment='Detailed notification text.'),
    sa.Column('type', sa.String(length=30), server_default='Task', nullable=False, comment="Notification category: 'Task', 'Interview', 'Progress', or 'Reminder'."),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='True if learner has marked this notification as read.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of creation.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('roadmap_id', sa.UUID(), nullable=False, comment='FK → career_roadmaps.id. Step is deleted with its roadmap.'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK → skills.id. RESTRICT prevents deleting a skill in-use.'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='1-based position of this step within the roadmap. Unique per roadmap.'),
    sa.Column('required', sa.Boolean(), server_default='true', nullable=False, comment='True = mandatory step. False = optional / enrichment material.'),
    sa.Column('estimated_hours', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False, comment='Estimated hours to complete this step. Must be >= 0.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.CheckConstraint('estimated_hours >= 0', name='ck_roadmap_steps_hours_non_negative'),
    sa.CheckConstraint('step_order >= 1', name='ck_roadmap_steps_order_positive'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['career_roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'skill_id', name='uq_roadmap_steps_roadmap_skill'),
    sa.UniqueConstraint('roadmap_id', 'step_order', name='uq_roadmap_steps_roadmap_order')
    )
    op.create_index(op.f('ix_roadmap_steps_required'), 'roadmap_steps', ['required'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_skill_id'), 'roadmap_steps', ['skill_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Human-readable task title.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional Markdown description of the task.'),
    sa.Column('instructions', sa.Text(), nullable=True, comment='Optional step-by-step instructions for the learner.'),
    sa.Column('difficulty', sa.String(length=20), server_default='Medium', nullable=False, comment="Difficulty level: 'Easy', 'Medium', or 'Hard'."),
    sa.Column('estimated_minutes', sa.Integer(), server_default='60', nullable=False, comment='Expected completion time in minutes. Must be >= 1.'),
    sa.Column('order_no', sa.Integer(), server_default='1', nullable=False, comment='1-based position within the parent roadmap step.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = hidden from learners. Prefer over hard DELETE.'),
    sa.Column('roadmap_step_id', sa.UUID(), nullable=False, comment='FK → roadmap_steps.id. Task is deleted when its step is deleted.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.CheckConstraint('estimated_minutes >= 1', name='ck_tasks_estimated_minutes_positive'),
    sa.CheckConstraint('order_no >= 1', name='ck_tasks_order_no_positive'),
    sa.ForeignKeyConstraint(['roadmap_step_id'], ['roadmap_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_difficulty'), 'tasks', ['difficulty'], unique=False)
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_tasks_roadmap_step_id'), 'tasks', ['roadmap_step_id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id. Progress is deleted when the user is deleted.'),
    sa.Column('skill_id', sa.UUID(), nullable=False, comment='FK → skills.id. Progress is deleted when the skill is deleted.'),
    sa.Column('current_step_id', sa.UUID(), nullable=True, comment='FK → roadmap_steps.id. Current roadmap step being pursued.'),
    sa.Column('completed_tasks', sa.Integer(), server_default='0', nullable=False, comment='Cumulative count of completed tasks.'),
    sa.Column('completed_interviews', sa.Integer(), server_default='0', nullable=False, comment='Cumulative count of completed interviews.'),
    sa.Column('status', sa.String(length=20), server_default='NOT_STARTED', nullable=False, comment="Lifecycle status: 'NOT_STARTED', 'IN_PROGRESS', or 'COMPLETED'."),
    sa.Column('progress_percentage', sa.Integer(), server_default='0', nullable=False, comment='Completion percentage 0–100. Enforced by CHECK constraint.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment="UTC timestamp of the learner's first interaction. NULL until begun."),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when the skill was marked completed. NULL until done.'),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of the most recent interaction. NULL until first access.'),
    sa.Column('time_spent_minutes', sa.Integer(), server_default='0', nullable=False, comment='Cumulative minutes spent learning this skill. Must be >= 0.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.CheckConstraint('progress_percentage BETWEEN 0 AND 100', name='ck_user_progress_percentage_range'),
    sa.CheckConstraint('time_spent_minutes >= 0', name='ck_user_progress_time_non_negative'),
    sa.ForeignKeyConstraint(['current_step_id'], ['roadmap_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_progress_user_skill')
    )
    op.create_index(op.f('ix_user_progress_current_step_id'), 'user_progress', ['current_step_id'], unique=False)
    op.create_index(op.f('ix_user_progress_skill_id'), 'user_progress', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_progress_status'), 'user_progress', ['status'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id. Interview deleted when user is deleted.'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='FK → tasks.id. Interview deleted when task is deleted.'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='Scheduled start time in UTC.'),
    sa.Column('duration_minutes', sa.Integer(), server_default='10', nullable=False, comment='Interview duration in minutes. Must be >= 1.'),
    sa.Column('status', sa.String(length=20), server_default='Scheduled', nullable=False, comment="Lifecycle status: 'Scheduled', 'Completed', 'Cancelled', 'Missed'."),
    sa.Column('meeting_link', sa.Text(), nullable=True, comment='Optional meeting link (e.g. video room URL).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.CheckConstraint('duration_minutes >= 1', name='ck_interviews_duration_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_index(op.f('ix_interviews_task_id'), 'interviews', ['task_id'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id. Submission is deleted when user is deleted.'),
    sa.Column('task_id', sa.UUID(), nullable=False, comment='FK → tasks.id. Submission is deleted when task is deleted.'),
    sa.Column('github_url', sa.Text(), nullable=True, comment="URL to the student's GitHub repository for this task."),
    sa.Column('submission_text', sa.Text(), nullable=True, comment='Free-text answer, notes, or explanation.'),
    sa.Column('file_url', sa.Text(), nullable=True, comment='URL to an uploaded file (S3 or local storage).'),
    sa.Column('status', sa.String(length=20), server_default='Pending', nullable=False, comment="Lifecycle status: 'Pending', 'Submitted', or 'Reviewed'."),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of submission creation. Immutable.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of last modification. Auto-updated.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_task_submissions_user_task')
    )
    op.create_index(op.f('ix_task_submissions_status'), 'task_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_task_submissions_task_id'), 'task_submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_submissions_user_id'), 'task_submissions', ['user_id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4.'),
    sa.Column('interview_id', sa.UUID(), nullable=False, comment='FK → interviews.id. Feedback deleted with interview.'),
    sa.Column('overall_score', sa.Integer(), server_default='0', nullable=False, comment='Overall aggregated score (0-100).'),
    sa.Column('technical_score', sa.Integer(), server_default='0', nullable=False, comment='Technical score (0-100).'),
    sa.Column('communication_score', sa.Integer(), server_default='0', nullable=False, comment='Communication score (0-100).'),
    sa.Column('confidence_score', sa.Integer(), server_default='0', nullable=False, comment='Confidence score (0-100).'),
    sa.Column('problem_solving_score', sa.Integer(), server_default='0', nullable=False, comment='Problem solving score (0-100).'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='Observed strengths during the interview.'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='Observed weaknesses during the interview.'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='Actionable suggestions for improvement.'),
    sa.Column('recommendation', sa.Text(), nullable=True, comment="Hiring recommendation (e.g. 'Strong Hire', 'Hire')."),
    sa.Column('status', sa.String(length=20), server_default='Generated', nullable=False, comment="Evaluation status: 'Pending' or 'Generated'."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of creation.'),
    sa.CheckConstraint('communication_score >= 0 AND communication_score <= 100', name='ck_interview_feedback_communication_score_range'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_interview_feedback_confidence_score_range'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_interview_feedback_overall_score_range'),
    sa.CheckConstraint('problem_solving_score >= 0 AND problem_solving_score <= 100', name='ck_interview_feedback_problem_solving_score_range'),
    sa.CheckConstraint('technical_score >= 0 AND technical_score <= 100', name='ck_interview_feedback_technical_score_range'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', name='uq_interview_feedback_interview_id')
    )
    op.create_index(op.f('ix_interview_feedback_interview_id'), 'interview_feedback', ['interview_id'], unique=True)
    op.create_index(op.f('ix_interview_feedback_status'), 'interview_feedback', ['status'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('interview_id', sa.UUID(), nullable=False, comment='FK → interviews.id. Question deleted when interview is deleted.'),
    sa.Column('question', sa.Text(), nullable=False, comment='The text prompt of the interview question.'),
    sa.Column('question_type', sa.String(length=20), server_default='Technical', nullable=False, comment="Question type: 'Technical' or 'Behavioral'."),
    sa.Column('difficulty', sa.String(length=20), server_default='Medium', nullable=False, comment="Difficulty: 'Easy', 'Medium', or 'Hard'."),
    sa.Column('order_no', sa.Integer(), server_default='1', nullable=False, comment='1-based sequence order of the question in the interview.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of creation.'),
    sa.CheckConstraint('order_no >= 1', name='ck_interview_questions_order_positive'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_difficulty'), 'interview_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_interview_questions_interview_id'), 'interview_questions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_question_type'), 'interview_questions', ['question_type'], unique=False)
    op.create_table('task_feedback',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4 generated by Python.'),
    sa.Column('submission_id', sa.UUID(), nullable=False, comment='FK → task_submissions.id. Feedback is deleted with submission.'),
    sa.Column('overall_score', sa.Integer(), server_default='0', nullable=False, comment='Overall aggregated score (0-100).'),
    sa.Column('technical_score', sa.Integer(), server_default='0', nullable=False, comment='Technical score (0-100).'),
    sa.Column('logic_score', sa.Integer(), server_default='0', nullable=False, comment='Logic score (0-100).'),
    sa.Column('code_quality_score', sa.Integer(), server_default='0', nullable=False, comment='Code quality score (0-100).'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='Observed strengths in the submission.'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='Observed weaknesses in the submission.'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='Actionable suggestions for improvement.'),
    sa.Column('status', sa.String(length=20), server_default='Generated', nullable=False, comment="Evaluation status: 'Pending' or 'Generated'."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation. Immutable.'),
    sa.CheckConstraint('code_quality_score >= 0 AND code_quality_score <= 100', name='ck_task_feedback_code_quality_score_range'),
    sa.CheckConstraint('logic_score >= 0 AND logic_score <= 100', name='ck_task_feedback_logic_score_range'),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_task_feedback_overall_score_range'),
    sa.CheckConstraint('technical_score >= 0 AND technical_score <= 100', name='ck_task_feedback_technical_score_range'),
    sa.ForeignKeyConstraint(['submission_id'], ['task_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_task_feedback_submission_id')
    )
    op.create_index(op.f('ix_task_feedback_status'), 'task_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_task_feedback_submission_id'), 'task_feedback', ['submission_id'], unique=True)
    op.create_table('interview_answers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate primary key — UUID v4.'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='FK → interview_questions.id.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id.'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment="Student's free-text response."),
    sa.Column('time_taken_seconds', sa.Integer(), server_default='0', nullable=False, comment='Time spent answering in seconds.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of creation.'),
    sa.CheckConstraint('time_taken_seconds >= 0', name='ck_interview_answers_time_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_interview_answers_question_user')
    )
    op.create_index(op.f('ix_interview_answers_question_id'), 'interview_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_interview_answers_user_id'), 'interview_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes introduced by this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answers_user_id'), table_name='interview_answers')
    op.drop_index(op.f('ix_interview_answers_question_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_task_feedback_submission_id'), table_name='task_feedback')
    op.drop_index(op.f('ix_task_feedback_status'), table_name='task_feedback')
    op.drop_table('task_feedback')
    op.drop_index(op.f('ix_interview_questions_question_type'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_interview_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_difficulty'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_feedback_status'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interview_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_task_submissions_user_id'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_task_id'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_status'), table_name='task_submissions')
    op.drop_table('task_submissions')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_task_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_status'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_skill_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_current_step_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_roadmap_step_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_difficulty'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_roadmap_steps_skill_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_required'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_skill_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_provider'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_free'), table_name='courses')
    op.drop_index(op.f('ix_courses_difficulty'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_career_roadmaps_title'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_profession_id'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_is_active'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_difficulty'), table_name='career_roadmaps')
    op.drop_table('career_roadmaps')
    # ### end Alembic commands ###
