"""
backend/app/models/course.py
------------------------------
ORM model for the ``courses`` table.

Table overview
--------------
``courses`` stores external learning resources (video lectures, MOOCs,
tutorials) that are tied to a specific skill.  Each course belongs to
exactly one ``Skill`` (one-to-many relationship).
Courses power the platform's personalised resource recommendations and
learning roadmap enrichment features.

Columns
-------
id              UUID PK — Python-generated (uuid4).
title           VARCHAR(500) NOT NULL — human display name of the course.
description     TEXT NULLABLE — rich Markdown description of the course.
provider        VARCHAR(255) NULLABLE — e.g. "Coursera", "Udemy", "YouTube".
course_url      TEXT NOT NULL — canonical URL to the course.
thumbnail_url   TEXT NULLABLE — URL to the course thumbnail image.
difficulty      VARCHAR(20) NOT NULL — Enum: 'Beginner', 'Intermediate', 'Advanced'.
duration_hours  NUMERIC(6,2) NULLABLE — estimated total hours to complete.
is_free         BOOLEAN NOT NULL DEFAULT false — whether the course is free.
rating          NUMERIC(3,2) NULLABLE — average rating 0.00–5.00.
skill_id        UUID FK → skills.id NOT NULL — owning skill.
created_at      TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at      TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Relationships
-------------
course.skill → Skill  (many-to-one, ``back_populates=\"courses\"``)

Registration
------------
Add the following line in ``app/db/base.py`` after creating this file::

    from app.models.course import Course  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Course(Base):
    """SQLAlchemy 2.x ORM model for the ``courses`` table.

    Represents an external learning resource (MOOC, tutorial, video lecture)
    associated with a career skill.  One ``Skill`` can have many ``Course``
    records (one-to-many).

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        title: Human-readable course title (e.g. "Python for Everybody").
        description: Optional long-form Markdown description of the course.
        provider: Optional publisher / platform name (e.g. "Coursera").
        course_url: Canonical URL to the course page. Required.
        thumbnail_url: Optional URL to a cover image / thumbnail.
        difficulty: Categorical difficulty level — one of
            ``'Beginner'``, ``'Intermediate'``, or ``'Advanced'``.
        duration_hours: Estimated hours to complete the course.
            ``None`` if unknown.
        is_free: ``True`` = course is available without payment.
        rating: Average community rating on a 0.00–5.00 scale.
            ``None`` if not yet rated.
        skill_id: Foreign key to the owning ``Skill`` row.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        skill: ORM relationship back to the owning ``Skill`` instance.
    """

    __tablename__ = "courses"

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Title ─────────────────────────────────────────────────────────────── #
    title: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        index=True,
        comment="Human-readable course title (e.g. 'Python for Everybody').",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional Markdown description of the course.",
    )

    # ── Provider ─────────────────────────────────────────────────────────── #
    provider: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        index=True,
        comment="Publishing platform or instructor (e.g. 'Coursera', 'Udemy').",
    )

    # ── Course URL ───────────────────────────────────────────────────────── #
    course_url: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Canonical URL to the course page. Required.",
    )

    # ── Thumbnail URL ────────────────────────────────────────────────────── #
    thumbnail_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="URL to the course cover image / thumbnail. Optional.",
    )

    # ── Difficulty ───────────────────────────────────────────────────────── #
    difficulty: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="Difficulty level: 'Beginner', 'Intermediate', or 'Advanced'.",
    )

    # ── Duration ─────────────────────────────────────────────────────────── #
    duration_hours: Mapped[float | None] = mapped_column(
        Numeric(precision=6, scale=2),
        nullable=True,
        comment="Estimated hours to complete the course. NULL if unknown.",
    )

    # ── Free flag ────────────────────────────────────────────────────────── #
    is_free: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        index=True,
        comment="True = course is available free of charge.",
    )

    # ── Rating ───────────────────────────────────────────────────────────── #
    rating: Mapped[float | None] = mapped_column(
        Numeric(precision=3, scale=2),
        nullable=True,
        comment="Average community rating on a 0.00–5.00 scale. NULL if unrated.",
    )

    # ── Foreign key — owning Skill ───────────────────────────────────────── #
    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → skills.id (owned by catalog-service). Plain UUID.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    skill: Mapped["Skill"] = relationship(  # type: ignore[name-defined]
        "Skill",
        back_populates="courses",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log (no secrets)."""
        return (
            f"Course("
            f"id={self.id!r}, "
            f"title={self.title!r}, "
            f"difficulty={self.difficulty!r}, "
            f"skill_id={self.skill_id!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable title — used in template rendering and f-string logs."""
        return self.title
