"""
backend/app/models/task_feedback.py
------------------------------------
ORM model for the ``task_feedback`` table.

Table overview
--------------
``task_feedback``
    Stores evaluation feedback for a learner's ``TaskSubmission``.
    Each record links to exactly one ``TaskSubmission`` via a UNIQUE foreign
    key constraint (one-to-one relationship).

Columns
-------
id                  UUID PK — Python-generated (uuid4).
submission_id       UUID FK → task_submissions.id NOT NULL UNIQUE — target submission.
overall_score       INTEGER NOT NULL — aggregated score (0–100).
technical_score     INTEGER NOT NULL — score for technical execution (0–100).
logic_score         INTEGER NOT NULL — score for logic/correctness (0–100).
code_quality_score  INTEGER NOT NULL — score for code structure & style (0–100).
strengths           TEXT NULLABLE — key strengths observed in the work.
weaknesses          TEXT NULLABLE — key areas of improvement.
suggestions         TEXT NULLABLE — actionable suggestions for the learner.
status              VARCHAR(20) NOT NULL DEFAULT 'Generated' — Enum: 'Pending', 'Generated'.
created_at          TIMESTAMPTZ NOT NULL — immutable creation timestamp.

Constraints
-----------
UNIQUE (submission_id) — exactly one feedback record per submission.
CHECK (overall_score BETWEEN 0 AND 100)
CHECK (technical_score BETWEEN 0 AND 100)
CHECK (logic_score BETWEEN 0 AND 100)
CHECK (code_quality_score BETWEEN 0 AND 100)

Relationships
-------------
task_feedback.submission → TaskSubmission (one-to-one, bidirectional)

Registration
------------
Add the following line in ``app/db/base.py``::

    from app.models.task_feedback import TaskFeedback  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.task import TaskSubmission  # noqa: F401


class TaskFeedback(Base):
    """SQLAlchemy 2.x ORM model for the ``task_feedback`` table.

    Represents evaluation feedback for a specific ``TaskSubmission``.
    Currently populated with rule-based/mock evaluation scores and feedback,
    structured for seamless transition to an AI LLM evaluation pipeline.

    Attributes:
        id: UUID primary key, generated by Python before INSERT.
        submission_id: FK to the evaluated ``TaskSubmission`` (UNIQUE).
        overall_score: Overall score percentage (0–100).
        technical_score: Technical implementation score (0–100).
        logic_score: Algorithm & logic score (0–100).
        code_quality_score: Code quality & style score (0–100).
        strengths: Markdown text describing strengths.
        weaknesses: Markdown text describing weaknesses.
        suggestions: Markdown text providing actionable advice.
        status: Feedback status — ``'Pending'`` or ``'Generated'``.
        created_at: UTC timestamp of creation (immutable).
        submission: ORM relationship to the evaluated ``TaskSubmission``.
    """

    __tablename__ = "task_feedback"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        UniqueConstraint(
            "submission_id",
            name="uq_task_feedback_submission_id",
        ),
        CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name="ck_task_feedback_overall_score_range",
        ),
        CheckConstraint(
            "technical_score >= 0 AND technical_score <= 100",
            name="ck_task_feedback_technical_score_range",
        ),
        CheckConstraint(
            "logic_score >= 0 AND logic_score <= 100",
            name="ck_task_feedback_logic_score_range",
        ),
        CheckConstraint(
            "code_quality_score >= 0 AND code_quality_score <= 100",
            name="ck_task_feedback_code_quality_score_range",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — TaskSubmission ────────────────────────────────────── #
    submission_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("task_submissions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="FK → task_submissions.id. Feedback is deleted with submission.",
    )

    # ── Scores ───────────────────────────────────────────────────────────── #
    overall_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Overall aggregated score (0-100).",
    )

    technical_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Technical score (0-100).",
    )

    logic_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Logic score (0-100).",
    )

    code_quality_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        comment="Code quality score (0-100).",
    )

    # ── Qualitative Feedback ────────────────────────────────────────────── #
    strengths: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Observed strengths in the submission.",
    )

    weaknesses: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Observed weaknesses in the submission.",
    )

    suggestions: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Actionable suggestions for improvement.",
    )

    # ── Status ───────────────────────────────────────────────────────────── #
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Generated",
        server_default="Generated",
        comment="Evaluation status: 'Pending' or 'Generated'.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    submission: Mapped["TaskSubmission"] = relationship(
        "TaskSubmission",
        back_populates="feedback",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"TaskFeedback("
            f"id={self.id!r}, "
            f"submission_id={self.submission_id!r}, "
            f"overall_score={self.overall_score!r}, "
            f"status={self.status!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary."""
        return f"Feedback {self.id} (submission={self.submission_id}, score={self.overall_score})"
