"""
backend/app/models/task.py
----------------------------
ORM models for the ``tasks`` and ``task_submissions`` tables.

Table overview
--------------
``tasks``
    A concrete learning exercise tied to a ``RoadmapStep``.  Each step in a
    career roadmap may have one or more tasks that the learner must complete
    to demonstrate competency in the underlying skill.  Tasks are ordered
    within their parent step via ``order_no``.

``task_submissions``
    A learner's submission against a ``Task``.  Each submission links exactly
    one ``User`` to one ``Task`` and carries the deliverables (GitHub URL,
    free-text answer, or uploaded file URL).  A UNIQUE constraint on
    ``(user_id, task_id)`` enforces at most one submission per user per task;
    re-submissions update the existing row.

Task Columns
------------
id                UUID PK — Python-generated (uuid4).
title             VARCHAR(500) NOT NULL — human display title.
description       TEXT NULLABLE — rich Markdown description.
instructions      TEXT NULLABLE — step-by-step instructions for the learner.
difficulty        VARCHAR(20) NOT NULL — Enum: 'Easy', 'Medium', 'Hard'.
estimated_minutes INTEGER NOT NULL DEFAULT 60 — expected time in minutes.
order_no          INTEGER NOT NULL DEFAULT 1 — position within the step.
is_active         BOOLEAN NOT NULL DEFAULT true — soft-delete flag.
roadmap_step_id   UUID FK → roadmap_steps.id NOT NULL — parent step.
created_at        TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at        TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

TaskSubmission Columns
----------------------
id                UUID PK — Python-generated (uuid4).
user_id           UUID FK → users.id NOT NULL — learner who submitted.
task_id           UUID FK → tasks.id NOT NULL — the task being submitted.
github_url        TEXT NULLABLE — URL to the student's GitHub repository.
submission_text   TEXT NULLABLE — free-text answer or notes.
file_url          TEXT NULLABLE — URL to an uploaded file (S3 / local).
status            VARCHAR(20) NOT NULL DEFAULT 'Pending' — submission lifecycle.
submitted_at      TIMESTAMPTZ NOT NULL — creation timestamp.
updated_at        TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Constraints
-----------
tasks:
    CHECK (estimated_minutes >= 1) — time must be positive.
    CHECK (order_no >= 1)         — ordering starts at 1.

task_submissions:
    UNIQUE (user_id, task_id)     — one submission per user per task.

Relationships
-------------
task.roadmap_step     → RoadmapStep       (many-to-one, unidirectional)
task.submissions      → [TaskSubmission]   (one-to-many, bidirectional)
submission.user       → User              (many-to-one, unidirectional)
submission.task       → Task              (many-to-one, bidirectional)

Registration
------------
Add the following line in ``app/db/base.py``::

    from app.models.task import Task, TaskSubmission  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

# ── TYPE_CHECKING guard ───────────────────────────────────────────────────── #
# Imported ONLY for static analysis.  At runtime these are resolved by
# SQLAlchemy's mapper via string references in ``relationship()``.
if TYPE_CHECKING:
    from app.models.career_roadmap import RoadmapStep  # noqa: F401
    from app.models.user import User  # noqa: F401
    from app.models.task_feedback import TaskFeedback  # noqa: F401


# =========================================================================== #
#  Task model                                                                   #
# =========================================================================== #


class Task(Base):
    """SQLAlchemy 2.x ORM model for the ``tasks`` table.

    Represents a concrete exercise or assignment within a ``RoadmapStep``.
    Tasks are the atomic unit of learning that students complete to progress
    through a career roadmap.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        title: Human-readable task title.
        description: Optional Markdown description of what the task covers.
        instructions: Optional detailed step-by-step instructions.
        difficulty: Categorical difficulty — ``'Easy'``, ``'Medium'``, ``'Hard'``.
        estimated_minutes: Expected time in minutes to complete (>= 1).
        order_no: 1-based position within the parent roadmap step.
        is_active: ``True`` = visible to learners.
        roadmap_step_id: FK to the parent ``RoadmapStep``.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        roadmap_step: ORM relationship to the parent ``RoadmapStep``.
        submissions: List of ``TaskSubmission`` records for this task.
    """

    __tablename__ = "tasks"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        CheckConstraint(
            "estimated_minutes >= 1",
            name="ck_tasks_estimated_minutes_positive",
        ),
        CheckConstraint(
            "order_no >= 1",
            name="ck_tasks_order_no_positive",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Title ────────────────────────────────────────────────────────────── #
    title: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        index=True,
        comment="Human-readable task title.",
    )

    # ── Description ──────────────────────────────────────────────────────── #
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional Markdown description of the task.",
    )

    # ── Instructions ─────────────────────────────────────────────────────── #
    instructions: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional step-by-step instructions for the learner.",
    )

    # ── Difficulty ───────────────────────────────────────────────────────── #
    difficulty: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Medium",
        server_default="Medium",
        comment="Difficulty level: 'Easy', 'Medium', or 'Hard'.",
    )

    # ── Estimated minutes ────────────────────────────────────────────────── #
    estimated_minutes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=60,
        server_default="60",
        comment="Expected completion time in minutes. Must be >= 1.",
    )

    # ── Order number ─────────────────────────────────────────────────────── #
    order_no: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default="1",
        comment="1-based position within the parent roadmap step.",
    )

    # ── Soft-delete flag ──────────────────────────────────────────────────── #
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        index=True,
        comment="False = hidden from learners. Prefer over hard DELETE.",
    )

    # ── Foreign key — RoadmapStep ────────────────────────────────────────── #
    roadmap_step_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → roadmap_steps.id (owned by catalog-service). Plain UUID.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    # Unidirectional — RoadmapStep model is NOT modified.
    roadmap_step: Mapped["RoadmapStep"] = relationship(  # type: ignore[name-defined]
        "RoadmapStep",
        lazy="select",
    )

    submissions: Mapped[list["TaskSubmission"]] = relationship(
        "TaskSubmission",
        back_populates="task",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="TaskSubmission.submitted_at.desc()",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"Task("
            f"id={self.id!r}, "
            f"title={self.title!r}, "
            f"difficulty={self.difficulty!r}, "
            f"roadmap_step_id={self.roadmap_step_id!r}, "
            f"is_active={self.is_active!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable title — used in f-string logs."""
        return self.title


# =========================================================================== #
#  TaskSubmission model                                                         #
# =========================================================================== #


class TaskSubmission(Base):
    """SQLAlchemy 2.x ORM model for the ``task_submissions`` table.

    Represents a learner's work submission for a specific ``Task``.  Each
    submission ties one ``User`` to one ``Task`` and carries deliverables
    (code repository URL, text answer, or file attachment).

    A UNIQUE constraint on ``(user_id, task_id)`` enforces one submission
    per user per task — re-submissions update the existing row rather than
    creating duplicates.

    The ``status`` field tracks the submission lifecycle:
      - ``Pending``   — submission created, awaiting content.
      - ``Submitted`` — learner has provided deliverables.
      - ``Reviewed``  — a mentor or AI has evaluated the submission.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        user_id: FK to the submitting ``User``.
        task_id: FK to the ``Task`` being submitted.
        github_url: Optional URL to a GitHub repository.
        submission_text: Optional free-text answer or notes.
        file_url: Optional URL to an uploaded file.
        status: Lifecycle status — ``'Pending'``, ``'Submitted'``, ``'Reviewed'``.
        submitted_at: UTC timestamp of submission creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        user: ORM relationship to the submitting ``User``.
        task: ORM relationship to the parent ``Task``.
    """

    __tablename__ = "task_submissions"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "task_id",
            name="uq_task_submissions_user_task",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — User ───────────────────────────────────────────────── #
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → users.id (owned by auth-service). Plain UUID.",
    )

    # ── Foreign key — Task ───────────────────────────────────────────────── #
    task_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tasks.id. Submission is deleted when task is deleted.",
    )

    # ── Deliverable fields ────────────────────────────────────────────────── #
    github_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="URL to the student's GitHub repository for this task.",
    )

    submission_text: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Free-text answer, notes, or explanation.",
    )

    file_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="URL to an uploaded file (S3 or local storage).",
    )

    deployment_url: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="URL to live deployed project instance.",
    )

    # ── Status ───────────────────────────────────────────────────────────── #
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        default="Pending",
        server_default="Pending",
        comment="Lifecycle status: 'Pending', 'Submitted', or 'Reviewed'.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of submission creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    # Unidirectional to User — User model is NOT modified.
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]
        "User",
        lazy="select",
    )

    task: Mapped["Task"] = relationship(
        "Task",
        back_populates="submissions",
        lazy="select",
    )

    feedback: Mapped[Optional["TaskFeedback"]] = relationship(  # type: ignore[name-defined]
        "TaskFeedback",
        back_populates="submission",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log."""
        return (
            f"TaskSubmission("
            f"id={self.id!r}, "
            f"user_id={self.user_id!r}, "
            f"task_id={self.task_id!r}, "
            f"status={self.status!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary — used in f-string logs."""
        return f"Submission {self.id} (user={self.user_id}, task={self.task_id}, status={self.status})"
