"""
services/agent-service/app/agents/agent4_interview.py
-------------------------------------------------------
Agent 4: AI-powered mock interview conductor.
- Uses questions generated by Agent 3
- Conducts the interview question-by-question
- Evaluates each answer and provides real-time feedback
- Scores communication, technical depth, and confidence
"""
from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.agents.llm_client import chat_complete, parse_json_response
from app.models.evaluation import Evaluation
from app.models.interview import Interview
from app.models.student import Student
from app.schemas.interview import (
    InterviewStartRequest,
    AnswerRequest,
    NextQuestionOut,
    AnswerFeedbackOut,
)

logger = logging.getLogger(__name__)

ANSWER_EVAL_SYSTEM = """You are a senior technical interviewer evaluating a candidate's answer.
Be fair, encouraging, and provide actionable feedback.
Return ONLY valid JSON. No markdown or extra text.
"""


def _build_answer_eval_prompt(question: str, answer: str, profession: str, experience: str) -> str:
    return f"""
The candidate is a {experience} {profession} student.

Interview question: "{question}"
Candidate's answer: "{answer}"

Evaluate their answer and return a JSON object:
{{
  "score": 0-100,
  "feedback": "2-3 sentence constructive feedback",
  "key_points_covered": ["point 1", "point 2"],
  "missed_points": ["missed 1", "missed 2"]
}}
"""


class InterviewAgent:
    """Agent 4 — conducts AI mock interviews question by question."""

    def start_interview(self, db: Session, request: InterviewStartRequest) -> Interview:
        """Initialize an interview session from an evaluation's generated questions."""
        evaluation = db.query(Evaluation).filter(
            Evaluation.id == request.evaluation_id,
            Evaluation.student_id == request.student_id,
        ).first()
        if not evaluation:
            raise ValueError("Evaluation not found for this student.")

        if not evaluation.interview_questions:
            raise ValueError("No interview questions found. Run evaluation first.")

        questions = json.loads(evaluation.interview_questions)
        if not questions:
            raise ValueError("Interview questions list is empty.")

        interview = Interview(
            student_id=request.student_id,
            evaluation_id=request.evaluation_id,
            total_questions=len(questions),
            current_question_index=0,
            qa_transcript=json.dumps([]),
            status="in_progress",
            started_at=datetime.now(timezone.utc),
        )
        db.add(interview)
        db.commit()
        db.refresh(interview)

        logger.info("Interview %s started for student %s with %d questions.",
                    interview.id, request.student_id, len(questions))
        return interview

    def get_next_question(self, db: Session, interview_id: uuid.UUID) -> NextQuestionOut | None:
        """Return the current unanswered question."""
        interview = db.query(Interview).filter(Interview.id == interview_id).first()
        if not interview or interview.status != "in_progress":
            return None

        evaluation = db.query(Evaluation).filter(
            Evaluation.id == interview.evaluation_id
        ).first()
        if not evaluation:
            return None

        questions = json.loads(evaluation.interview_questions or "[]")
        idx = interview.current_question_index
        if idx >= len(questions):
            return None

        return NextQuestionOut(
            interview_id=interview_id,
            question_index=idx,
            question=questions[idx],
            total_questions=len(questions),
            is_last=(idx == len(questions) - 1),
        )

    def submit_answer(self, db: Session, request: AnswerRequest) -> AnswerFeedbackOut:
        """Evaluate an answer and advance to next question."""
        interview = db.query(Interview).filter(Interview.id == request.interview_id).first()
        if not interview:
            raise ValueError("Interview not found.")
        if interview.status != "in_progress":
            raise ValueError("Interview is not in progress.")
        if request.question_index != interview.current_question_index:
            raise ValueError("Question index mismatch.")

        evaluation = db.query(Evaluation).filter(
            Evaluation.id == interview.evaluation_id
        ).first()
        student = db.query(Student).filter(Student.id == interview.student_id).first()

        questions = json.loads(evaluation.interview_questions or "[]")
        question = questions[request.question_index]

        # Evaluate answer via LLM
        prompt = _build_answer_eval_prompt(
            question=question,
            answer=request.answer,
            profession=student.profession if student else "software development",
            experience=student.experience_level if student else "beginner",
        )
        raw = chat_complete(ANSWER_EVAL_SYSTEM, prompt)
        feedback_data = parse_json_response(raw)

        if isinstance(feedback_data, dict) and "mock" in feedback_data:
            feedback_data = {
                "score": 70,
                "feedback": "Good attempt. Your answer covers the basics. Try to elaborate with real examples next time.",
                "key_points_covered": ["Mentioned core concept"],
                "missed_points": ["Depth of explanation", "Real-world examples"],
            }

        score = int(feedback_data.get("score", 70))
        feedback_text = feedback_data.get("feedback", "")

        # Append to transcript
        transcript = json.loads(interview.qa_transcript or "[]")
        transcript.append({
            "question_index": request.question_index,
            "question": question,
            "answer": request.answer,
            "score": score,
            "feedback": feedback_text,
            "key_points_covered": feedback_data.get("key_points_covered", []),
            "missed_points": feedback_data.get("missed_points", []),
        })
        interview.qa_transcript = json.dumps(transcript)

        # Advance question
        interview.current_question_index += 1
        is_complete = interview.current_question_index >= len(questions)

        if is_complete:
            # Calculate final scores
            scores = [entry["score"] for entry in transcript]
            avg = sum(scores) / len(scores) if scores else 0
            interview.overall_score = int(avg)
            interview.technical_score = int(avg)  # Can refine per-category later
            interview.communication_score = min(100, int(avg + 5))
            interview.confidence_score = min(100, int(avg - 5))
            interview.status = "completed"
            interview.completed_at = datetime.now(timezone.utc)
            logger.info("Interview %s completed. Score: %d", interview.id, interview.overall_score)

        db.commit()
        db.refresh(interview)

        next_q = questions[interview.current_question_index] if not is_complete else None

        return AnswerFeedbackOut(
            question=question,
            your_answer=request.answer,
            score=score,
            feedback=feedback_text,
            next_question=next_q,
            is_complete=is_complete,
        )

    def get_interview(self, db: Session, interview_id: uuid.UUID) -> Interview | None:
        return db.query(Interview).filter(Interview.id == interview_id).first()

    def get_student_interviews(self, db: Session, student_id: uuid.UUID) -> list[Interview]:
        return (
            db.query(Interview)
            .filter(Interview.student_id == student_id)
            .order_by(Interview.created_at.desc())
            .all()
        )


# Singleton
interview_agent = InterviewAgent()
