"""
backend/app/models/learning_path.py
--------------------------------------
ORM model for the ``learning_paths`` table.

Table overview
--------------
``learning_paths`` is an **association / junction table** that prescribes the
ordered sequence of Skills a learner must complete to master a given Profession.
It bridges ``professions`` ↔ ``skills`` with extra payload columns that
describe *how* the skill fits into the learning journey.

Columns
-------
id               UUID PK — Python-generated (uuid4).
profession_id    UUID FK → professions.id NOT NULL — owning career path.
skill_id         UUID FK → skills.id NOT NULL — the skill in the path.
sequence         INTEGER NOT NULL — 1-based position in the learning order.
estimated_weeks  INTEGER NOT NULL DEFAULT 1 — expected study time in weeks.
is_required      BOOLEAN NOT NULL DEFAULT true — required vs. optional skill.
created_at       TIMESTAMPTZ NOT NULL — immutable; set by DB on INSERT.
updated_at       TIMESTAMPTZ NOT NULL — refreshed by DB on every UPDATE.

Constraints
-----------
UNIQUE (profession_id, sequence)  — no two entries share the same step number
                                    within one profession.
UNIQUE (profession_id, skill_id)  — a skill appears at most once per profession
                                    path.

Relationships
-------------
learning_path.profession → Profession  (many-to-one)
learning_path.skill      → Skill       (many-to-one)

Registration
------------
Add the following line in ``app/db/base.py``::

    from app.models.learning_path import LearningPath  # noqa: F401
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class LearningPath(Base):
    """SQLAlchemy 2.x ORM model for the ``learning_paths`` table.

    Represents a single ordered step in a profession's learning journey.
    Each row links one ``Profession`` to one ``Skill`` and annotates the
    relationship with sequencing, time estimates, and an optional flag.

    Attributes:
        id: UUID primary key, generated by Python before the INSERT.
        profession_id: FK to the ``Profession`` that owns this learning path.
        skill_id: FK to the ``Skill`` that is studied at this step.
        sequence: 1-based integer ordering the step within the profession
            path.  Must be unique per profession.
        estimated_weeks: Indicative number of weeks to complete this step.
            Must be >= 1.
        is_required: ``True`` = learners must complete this step to finish
            the path.  ``False`` = optional / enrichment material.
        created_at: UTC timestamp of row creation (immutable).
        updated_at: UTC timestamp of last modification (auto-updated).
        profession: ORM relationship to the owning ``Profession`` instance.
        skill: ORM relationship to the linked ``Skill`` instance.
    """

    __tablename__ = "learning_paths"

    # ── Table-level constraints ───────────────────────────────────────────── #
    __table_args__ = (
        UniqueConstraint(
            "profession_id",
            "sequence",
            name="uq_learning_paths_profession_sequence",
        ),
        UniqueConstraint(
            "profession_id",
            "skill_id",
            name="uq_learning_paths_profession_skill",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────── #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="Surrogate primary key — UUID v4 generated by Python.",
    )

    # ── Foreign key — Profession ──────────────────────────────────────────── #
    profession_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("professions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → professions.id. Entry is removed when the profession is deleted.",
    )

    # ── Foreign key — Skill ──────────────────────────────────────────────── #
    skill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("skills.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → skills.id. Entry is removed when the skill is deleted.",
    )

    # ── Sequence ─────────────────────────────────────────────────────────── #
    sequence: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        index=True,
        comment="1-based step number within the profession path. Unique per profession.",
    )

    # ── Estimated weeks ──────────────────────────────────────────────────── #
    estimated_weeks: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default="1",
        comment="Expected number of weeks to complete this step. Must be >= 1.",
    )

    # ── Required flag ────────────────────────────────────────────────────── #
    is_required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
        index=True,
        comment="True = mandatory for path completion. False = optional enrichment.",
    )

    # ── Timestamps ───────────────────────────────────────────────────────── #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp of row creation. Immutable.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="UTC timestamp of last modification. Auto-updated.",
    )

    # ── Relationships ─────────────────────────────────────────────────────── #
    profession: Mapped["Profession"] = relationship(  # type: ignore[name-defined]
        "Profession",
        back_populates="learning_paths",
        lazy="select",
    )

    skill: Mapped["Skill"] = relationship(  # type: ignore[name-defined]
        "Skill",
        back_populates="learning_paths",
        lazy="select",
    )

    # ── Dunder methods ────────────────────────────────────────────────────── #

    def __repr__(self) -> str:
        """Unambiguous developer representation — safe to log (no secrets)."""
        return (
            f"LearningPath("
            f"id={self.id!r}, "
            f"profession_id={self.profession_id!r}, "
            f"skill_id={self.skill_id!r}, "
            f"sequence={self.sequence!r}, "
            f"is_required={self.is_required!r}"
            f")"
        )

    def __str__(self) -> str:
        """Human-readable summary — used in f-string logs."""
        return f"Step {self.sequence} (profession={self.profession_id}, skill={self.skill_id})"
